#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Village Wallet
* APIs for Village Wallet
*
* The version of the OpenAPI document: 0.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIBasketItems.h"
@protocol OAIBasketItems;
@class OAIBasketItems;



@protocol OAIBasket
@end

@interface OAIBasket : OAIObject

/* An array of items in the basket [optional]
 */
@property(nonatomic) NSArray<OAIBasketItems>* items;

@end
