#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIChargePaymentAgreementRequestTransactionType.h"
#import "OAIVerifyPaymentInstrumentsRequestFraudPayload.h"
@protocol OAIChargePaymentAgreementRequestTransactionType;
@class OAIChargePaymentAgreementRequestTransactionType;
@protocol OAIVerifyPaymentInstrumentsRequestFraudPayload;
@class OAIVerifyPaymentInstrumentsRequestFraudPayload;



@protocol OAIChargePaymentAgreementRequest
@end

@interface OAIChargePaymentAgreementRequest : OAIObject


@property(nonatomic) OAIChargePaymentAgreementRequestTransactionType* transactionType;
/* A merchant application specific reference number. This number should uniquely identify the transaction in the merchant’s system. 
 */
@property(nonatomic) NSString* clientReference;
/* A merchant application specific reference number. This number should uniquely identify the customer in the merchant’s system. [optional]
 */
@property(nonatomic) NSString* customerRef;
/* The merchant order number of the transaction. 
 */
@property(nonatomic) NSString* orderNumber;
/* The payment token of the payment agreement. The payment token is a unique identifier for the payment agreement. 
 */
@property(nonatomic) NSString* paymentToken;
/* The amount that will be charged against the payment instrument linked to the payment agreement. 
 */
@property(nonatomic) NSNumber* amount;

@property(nonatomic) OAIVerifyPaymentInstrumentsRequestFraudPayload* fraudPayload;

@end
