#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIQr.h"
@protocol OAIQr;
@class OAIQr;



@protocol OAICreateMerchantPaymentSessionResponseData
@end

@interface OAICreateMerchantPaymentSessionResponseData : OAIObject

/* The ID of the new payment session 
 */
@property(nonatomic) NSString* paymentSessionId;

@property(nonatomic) OAIQr* qr;

@end
