#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAICustomerTermsAndConditionsAcceptance.h"
@protocol OAICustomerTermsAndConditionsAcceptance;
@class OAICustomerTermsAndConditionsAcceptance;



@protocol OAICustomerTermsAndConditionsResultData
@end

@interface OAICustomerTermsAndConditionsResultData : OAIObject

/* An array of Ts and Cs the customer has accepted. [optional]
 */
@property(nonatomic) NSArray<OAICustomerTermsAndConditionsAcceptance>* termsAndConditionsAcceptances;

@end
