#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Village Wallet
* APIs for Village Wallet
*
* The version of the OpenAPI document: 0.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAICustomerPaymentsPaymentRequestIdDataSecondaryInstruments
@end

@interface OAICustomerPaymentsPaymentRequestIdDataSecondaryInstruments : OAIObject

/* The ID of the payment instrument 
 */
@property(nonatomic) NSString* instrumentId;
/* The amount to charged against this instrument.  Must be greater than zero 
 */
@property(nonatomic) NSNumber* amount;

@end
