#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIBasket.h"
@protocol OAIBasket;
@class OAIBasket;



@protocol OAICustomerPaymentRequestDetailsAllOf
@end

@interface OAICustomerPaymentRequestDetailsAllOf : OAIObject

/* The ID of the merchant associated with this transaction 
 */
@property(nonatomic) NSString* merchantId;

@property(nonatomic) OAIBasket* basket;

@end
