#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAICreatePaymentRequestResultsData.h"
#import "OAIMeta.h"
@protocol OAICreatePaymentRequestResultsData;
@class OAICreatePaymentRequestResultsData;
@protocol OAIMeta;
@class OAIMeta;



@protocol OAICreatePaymentRequestResults
@end

@interface OAICreatePaymentRequestResults : OAIObject


@property(nonatomic) OAICreatePaymentRequestResultsData* data;

@property(nonatomic) OAIMeta* meta;

@end
