#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIInstoreCustomerTermsandconditionsAcceptanceData.h"
@protocol OAIInstoreCustomerTermsandconditionsAcceptanceData;
@class OAIInstoreCustomerTermsandconditionsAcceptanceData;



@protocol OAICustomerTermsAndConditions
@end

@interface OAICustomerTermsAndConditions : OAIObject


@property(nonatomic) OAIInstoreCustomerTermsandconditionsAcceptanceData* data;
/* Object to contain any metadata [optional]
 */
@property(nonatomic) NSDictionary<NSString*, NSObject*>* meta;

@end
