#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIMerchantSchemaSummary.h"
#import "OAIMeta.h"
@protocol OAIMerchantSchemaSummary;
@class OAIMerchantSchemaSummary;
@protocol OAIMeta;
@class OAIMeta;



@protocol OAICreateMerchantSchemaResults
@end

@interface OAICreateMerchantSchemaResults : OAIObject


@property(nonatomic) OAIMerchantSchemaSummary* data;

@property(nonatomic) OAIMeta* meta;

@end
