#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAICustomerTermsAndConditionsResultData.h"
#import "OAIMeta.h"
@protocol OAICustomerTermsAndConditionsResultData;
@class OAICustomerTermsAndConditionsResultData;
@protocol OAIMeta;
@class OAIMeta;



@protocol OAICustomerTermsAndConditionsResult
@end

@interface OAICustomerTermsAndConditionsResult : OAIObject


@property(nonatomic) OAICustomerTermsAndConditionsResultData* data;

@property(nonatomic) OAIMeta* meta;

@end
