#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAICompletionsSuccessResponseCompletionResponses.h"
@protocol OAICompletionsSuccessResponseCompletionResponses;
@class OAICompletionsSuccessResponseCompletionResponses;



@protocol OAICompletionsSuccessResponse
@end

@interface OAICompletionsSuccessResponse : OAIObject

/* Container reference in the transaction logs. This number uniquely identifies the whole/grouped transaction in the container. 
 */
@property(nonatomic) NSString* transactionReceipt;
/* A flag to indicate if a split completion was only partially successful, ie. at least 1 of the completions had a successful result. 
 */
@property(nonatomic) NSNumber* partialSuccess;

@property(nonatomic) NSArray<OAICompletionsSuccessResponseCompletionResponses>* completionResponses;

@end
