#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Village Wallet
* APIs for Village Wallet
*
* The version of the OpenAPI document: 0.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAICustomerTransactionSummaryAllOfInstruments.h"
@protocol OAICustomerTransactionSummaryAllOfInstruments;
@class OAICustomerTransactionSummaryAllOfInstruments;



@protocol OAICustomerTransactionSummaryAllOf
@end

@interface OAICustomerTransactionSummaryAllOf : OAIObject

/* The ID of the merchant associated with this transaction 
 */
@property(nonatomic) NSString* merchantId;
/* The instruments used to make the payment.  For refunds and cash back amounts will be negative 
 */
@property(nonatomic) NSArray<OAICustomerTransactionSummaryAllOfInstruments>* instruments;

@end
