#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIInstoreCustomerPaymentsPaymentRequestIdData.h"
#import "OAIMetaChallenge.h"
@protocol OAIInstoreCustomerPaymentsPaymentRequestIdData;
@class OAIInstoreCustomerPaymentsPaymentRequestIdData;
@protocol OAIMetaChallenge;
@class OAIMetaChallenge;



@protocol OAICustomerPaymentDetails
@end

@interface OAICustomerPaymentDetails : OAIObject


@property(nonatomic) OAIInstoreCustomerPaymentsPaymentRequestIdData* data;

@property(nonatomic) OAIMetaChallenge* meta;

@end
