#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Village Wallet
* APIs for Village Wallet
*
* The version of the OpenAPI document: 0.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAICustomerPaymentsPaymentRequestIdData.h"
#import "OAIMetaChallenge.h"
@protocol OAICustomerPaymentsPaymentRequestIdData;
@class OAICustomerPaymentsPaymentRequestIdData;
@protocol OAIMetaChallenge;
@class OAIMetaChallenge;



@protocol OAICustomerPaymentDetails1
@end

@interface OAICustomerPaymentDetails1 : OAIObject


@property(nonatomic) OAICustomerPaymentsPaymentRequestIdData* data;

@property(nonatomic) OAIMetaChallenge* meta;

@end
