#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Village Wallet
* APIs for Village Wallet
*
* The version of the OpenAPI document: 0.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAICommonPaymentBase.h"
#import "OAICommonPaymentSummaryAllOf.h"
@protocol OAICommonPaymentBase;
@class OAICommonPaymentBase;
@protocol OAICommonPaymentSummaryAllOf;
@class OAICommonPaymentSummaryAllOf;



@protocol OAICommonPaymentSummary
@end

@interface OAICommonPaymentSummary : OAIObject

/* The ID of this payment request 
 */
@property(nonatomic) NSString* paymentRequestId;
/* The unique reference for the payment as defined by the Merchant 
 */
@property(nonatomic) NSString* merchantReferenceId;
/* The gross amount to be paid.  Must be positive except for refunds 
 */
@property(nonatomic) NSNumber* grossAmount;
/* The ISO date/time that the payment request was created 
 */
@property(nonatomic) NSString* createdTime;

@end
