#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAICompletionsErrorResponseAllOf.h"
#import "OAICompletionsErrorResponseAllOfCompletionResponses.h"
#import "OAIError.h"
@protocol OAICompletionsErrorResponseAllOf;
@class OAICompletionsErrorResponseAllOf;
@protocol OAICompletionsErrorResponseAllOfCompletionResponses;
@class OAICompletionsErrorResponseAllOfCompletionResponses;
@protocol OAIError;
@class OAIError;



@protocol OAICompletionsErrorResponse
@end

@interface OAICompletionsErrorResponse : OAIObject

/* The http status code (4xx and 5xx HTTP status codes). 
 */
@property(nonatomic) NSNumber* httpStatusCode;
/* The error code. 
 */
@property(nonatomic) NSString* errorCode;
/* The error message. 
 */
@property(nonatomic) NSString* errorMessage;
/* The error detail. 
 */
@property(nonatomic) NSString* errorDetail;

@property(nonatomic) NSArray<OAICompletionsErrorResponseAllOfCompletionResponses>* completionResponses;

@end
