#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Village Wallet
* APIs for Village Wallet
*
* The version of the OpenAPI document: 0.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIDynamicPayload
@end

@interface OAIDynamicPayload : OAIObject

/* The ID of the previously configured schema that will be used to validate the contents of the payload [optional]
 */
@property(nonatomic) NSString* schemaId;
/* The payload aligned to the supplied schema [optional]
 */
@property(nonatomic) NSDictionary<NSString*, NSObject*>* payload;

@end
