#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Village Wallet
* APIs for Village Wallet
*
* The version of the OpenAPI document: 0.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIError
@end

@interface OAIError : OAIObject

/* The http status code (4xx and 5xx HTTP status codes) 
 */
@property(nonatomic) NSNumber* httpStatusCode;
/* The error code 
 */
@property(nonatomic) NSString* errorCode;
/* The error message 
 */
@property(nonatomic) NSString* errorMessage;
/* The error detail 
 */
@property(nonatomic) NSString* errorDetail;

@end
