#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIGiftingProductDesign
@end

@interface OAIGiftingProductDesign : OAIObject

/* Unique (within the scope of designType) identifier of the aesthectic design of the gift card 
 */
@property(nonatomic) NSString* designId;
/* Format of the design (note that different design types have different unique IDs) 
 */
@property(nonatomic) NSString* designType;
/* URL to the image for the gift card design 
 */
@property(nonatomic) NSString* imageUrl;

@end
