#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIGiftcardsBalanceRequestGiftCardInstruments.h"
#import "OAIGiftcardsBalanceRequestGiftCards.h"
@protocol OAIGiftcardsBalanceRequestGiftCardInstruments;
@class OAIGiftcardsBalanceRequestGiftCardInstruments;
@protocol OAIGiftcardsBalanceRequestGiftCards;
@class OAIGiftcardsBalanceRequestGiftCards;



@protocol OAIGiftcardsBalanceRequest
@end

@interface OAIGiftcardsBalanceRequest : OAIObject

/* Use this array if the endpoint is being called with \"cardNumber\" and \"pinCode\" request properties. [optional]
 */
@property(nonatomic) NSArray<OAIGiftcardsBalanceRequestGiftCards>* giftCards;
/* Use this array if the endpoint is being called with \"paymentInstrumentId\" request properties. [optional]
 */
@property(nonatomic) NSArray<OAIGiftcardsBalanceRequestGiftCardInstruments>* giftCardInstruments;

@end
