#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Village Wallet
* APIs for Village Wallet
*
* The version of the OpenAPI document: 0.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIGetMerchantTransactionsResultsData.h"
#import "OAIMetaPaginated.h"
@protocol OAIGetMerchantTransactionsResultsData;
@class OAIGetMerchantTransactionsResultsData;
@protocol OAIMetaPaginated;
@class OAIMetaPaginated;



@protocol OAIGetMerchantTransactionsResults
@end

@interface OAIGetMerchantTransactionsResults : OAIObject


@property(nonatomic) OAIGetMerchantTransactionsResultsData* data;

@property(nonatomic) OAIMetaPaginated* meta;

@end
