#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIGiftingProductDiscount
@end

@interface OAIGiftingProductDiscount : OAIObject

/* Unique identifier of the discount 
 */
@property(nonatomic) NSString* discountId;
/* Display description of the discount 
 */
@property(nonatomic) NSString* _description;
/* Percentage discount offered on the gift card 
 */
@property(nonatomic) NSNumber* percentageDiscount;
/* The start date of the offered discount. The timestamp format is ISO8601. [optional]
 */
@property(nonatomic) NSString* startDate;
/* The end date of the offered discount. The timestamp format is ISO8601. [optional]
 */
@property(nonatomic) NSString* endDate;

@end
