#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIMerchantPaymentSummary.h"
@protocol OAIMerchantPaymentSummary;
@class OAIMerchantPaymentSummary;



@protocol OAIGetMerchantPaymentsResultsData
@end

@interface OAIGetMerchantPaymentsResultsData : OAIObject

/* The resulting list of payments.  If no results match the request then an empty array will be returned 
 */
@property(nonatomic) NSArray<OAIMerchantPaymentSummary>* payments;

@end
