#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIGiftingProduct.h"
#import "OAIGiftingProductDesign.h"
#import "OAIGiftingProductDetailAllOf.h"
#import "OAIGiftingProductDiscount.h"
@protocol OAIGiftingProduct;
@class OAIGiftingProduct;
@protocol OAIGiftingProductDesign;
@class OAIGiftingProductDesign;
@protocol OAIGiftingProductDetailAllOf;
@class OAIGiftingProductDetailAllOf;
@protocol OAIGiftingProductDiscount;
@class OAIGiftingProductDiscount;



@protocol OAIGiftingProductDetail
@end

@interface OAIGiftingProductDetail : OAIObject

/* Unique identifier assigned to gift card program 
 */
@property(nonatomic) NSString* productId;
/* Display name of the gift card program 
 */
@property(nonatomic) NSString* name;
/* The manner in which the barcode is displayed for optical recognition (can be used to drive CX experience flows) 
 */
@property(nonatomic) NSString* barCodeType;
/* The timestamp the gift card program was last updated. The timestamp format is ISO8601. 
 */
@property(nonatomic) NSString* lastUpdateDateTime;

@property(nonatomic) OAIGiftingProductDesign* defaultDesign;

@property(nonatomic) OAIGiftingProductDiscount* discountOffered;
/* Display instruction on where and how to redeem the product [optional]
 */
@property(nonatomic) NSString* redemptionInstructions;
/* The enabled redemption channels 
 */
@property(nonatomic) NSString* redemptionType;
/* Terms and conditions text for the gift card product [optional]
 */
@property(nonatomic) NSString* termsAndConditions;
/* Minimum AUD value gift card able to be purchased for this product 
 */
@property(nonatomic) NSNumber* minValue;
/* Maximum AUD value gift card able to be purchased for this product 
 */
@property(nonatomic) NSNumber* maxValue;
/* Expiry period for the gift card product once purchased [optional]
 */
@property(nonatomic) NSNumber* expiryPeriodInDays;
/* Display text for the expiry period [optional]
 */
@property(nonatomic) NSString* expiryPeriodText;
/* Returns true if the gift card product is active, else false. Only active programs are orderable 
 */
@property(nonatomic) NSNumber* isActive;
/* The stores in which the gift card product is able to be redeemed [optional]
 */
@property(nonatomic) NSArray<NSString*>* redemptionStores;
/* Digital or phyiscal availability of the gift card 
 */
@property(nonatomic) NSString* availability;
/* Array of all alternative designs for the gift card product 
 */
@property(nonatomic) NSArray<OAIGiftingProductDesign>* designs;

@end
