#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIGiftcardsBalanceRequestGiftCards
@end

@interface OAIGiftcardsBalanceRequestGiftCards : OAIObject

/* The gift card number. 
 */
@property(nonatomic) NSString* cardNumber;
/* The gift card pin code. 
 */
@property(nonatomic) NSString* pinCode;

@end
