#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Village Wallet
* APIs for Village Wallet
*
* The version of the OpenAPI document: 0.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIGetMerchantPaymentsResultsData.h"
#import "OAIMetaPaginated.h"
@protocol OAIGetMerchantPaymentsResultsData;
@class OAIGetMerchantPaymentsResultsData;
@protocol OAIMetaPaginated;
@class OAIMetaPaginated;



@protocol OAIGetMerchantPaymentsResults
@end

@interface OAIGetMerchantPaymentsResults : OAIObject


@property(nonatomic) OAIGetMerchantPaymentsResultsData* data;

@property(nonatomic) OAIMetaPaginated* meta;

@end
