#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIGiftingProductOrderRequestData.h"
#import "OAIMeta.h"
@protocol OAIGiftingProductOrderRequestData;
@class OAIGiftingProductOrderRequestData;
@protocol OAIMeta;
@class OAIMeta;



@protocol OAIGiftingProductOrderRequest
@end

@interface OAIGiftingProductOrderRequest : OAIObject


@property(nonatomic) OAIGiftingProductOrderRequestData* data;

@property(nonatomic) OAIMeta* meta;

@end
