#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAICustomerPaymentRequestDetails.h"
#import "OAIMeta.h"
@protocol OAICustomerPaymentRequestDetails;
@class OAICustomerPaymentRequestDetails;
@protocol OAIMeta;
@class OAIMeta;



@protocol OAIGetCustomerPaymentRequestResult
@end

@interface OAIGetCustomerPaymentRequestResult : OAIObject


@property(nonatomic) OAICustomerPaymentRequestDetails* data;

@property(nonatomic) OAIMeta* meta;

@end
