#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIMerchantPaymentDetails.h"
#import "OAIMeta.h"
@protocol OAIMerchantPaymentDetails;
@class OAIMerchantPaymentDetails;
@protocol OAIMeta;
@class OAIMeta;



@protocol OAIGetMerchantPaymentDetailsResults
@end

@interface OAIGetMerchantPaymentDetailsResults : OAIObject


@property(nonatomic) OAIMerchantPaymentDetails* data;

@property(nonatomic) OAIMeta* meta;

@end
