#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAICustomerTransactionDetail.h"
#import "OAIMeta.h"
@protocol OAICustomerTransactionDetail;
@class OAICustomerTransactionDetail;
@protocol OAIMeta;
@class OAIMeta;



@protocol OAIGetCustomerTransactionDetailsResults
@end

@interface OAIGetCustomerTransactionDetailsResults : OAIObject


@property(nonatomic) OAICustomerTransactionDetail* data;

@property(nonatomic) OAIMeta* meta;

@end
