#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Village Wallet
* APIs for Village Wallet
*
* The version of the OpenAPI document: 0.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIGetCustomerTransactionsResultData.h"
#import "OAIMetaPaginated.h"
@protocol OAIGetCustomerTransactionsResultData;
@class OAIGetCustomerTransactionsResultData;
@protocol OAIMetaPaginated;
@class OAIMetaPaginated;



@protocol OAIGetCustomerTransactionsResult
@end

@interface OAIGetCustomerTransactionsResult : OAIObject


@property(nonatomic) OAIGetCustomerTransactionsResultData* data;

@property(nonatomic) OAIMetaPaginated* meta;

@end
