#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Village Wallet
* APIs for Village Wallet
*
* The version of the OpenAPI document: 0.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIGiftCardStepUp
@end

@interface OAIGiftCardStepUp : OAIObject

/* The type of the step up action. For gift cards this will be REQUIRE_PASSCODE which identifies that the consumer must capture the PIN prior to payment. 
 */
@property(nonatomic) NSString* type;
/* A flag to indicate if this step up (action) is mandatory. 
 */
@property(nonatomic) NSNumber* mandatory;

@end
