#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIGuestTokenizeApplePayRequest
@end

@interface OAIGuestTokenizeApplePayRequest : OAIObject

/* The \"data\" value from the Apple Pay wallet. 
 */
@property(nonatomic) NSString* data;
/* The \"ephemeralPublicKey\" value from the Apple Pay wallet. 
 */
@property(nonatomic) NSString* ephemeralPublicKey;
/* The \"publicKeyHash\" value from the Apple Pay wallet. 
 */
@property(nonatomic) NSString* publicKeyHash;
/* The \"transactionId\" value from the Apple Pay wallet. 
 */
@property(nonatomic) NSString* transactionId;
/* The \"signature\" value from the Apple Pay wallet. 
 */
@property(nonatomic) NSString* signature;
/* The \"version\" value from the Apple Pay wallet. 
 */
@property(nonatomic) NSString* version;
/* The type/schema value from the Apple Pay wallet. 
 */
@property(nonatomic) NSString* instrumentType;
/* The display text returned by the Apple Pay wallet. 
 */
@property(nonatomic) NSString* comment;
/* The \"applicationData\" value from the Apple Pay wallet. 
 */
@property(nonatomic) NSString* applicationData;

@end
