#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIInlineResponse2003Data.h"
#import "OAIMeta.h"
@protocol OAIInlineResponse2003Data;
@class OAIInlineResponse2003Data;
@protocol OAIMeta;
@class OAIMeta;



@protocol OAIInlineResponse2003
@end

@interface OAIInlineResponse2003 : OAIObject


@property(nonatomic) OAIInlineResponse2003Data* data;

@property(nonatomic) OAIMeta* meta;

@end
