#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIInstrumentAllocationTransactions.h"
@protocol OAIInstrumentAllocationTransactions;
@class OAIInstrumentAllocationTransactions;



@protocol OAIInstrumentAllocation
@end

@interface OAIInstrumentAllocation : OAIObject

/* The ID of the payment instrument 
 */
@property(nonatomic) NSString* paymentInstrumentId;
/* The type of the payment instrument. 
 */
@property(nonatomic) NSString* instrumentType;
/* The list of transactions associated with the instrument.  If no results match the request then an empty array will be returned 
 */
@property(nonatomic) NSArray<OAIInstrumentAllocationTransactions>* transactions;

@end
