#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIImmediatePaymentRequestData.h"
#import "OAIMeta.h"
@protocol OAIImmediatePaymentRequestData;
@class OAIImmediatePaymentRequestData;
@protocol OAIMeta;
@class OAIMeta;



@protocol OAIImmediatePaymentRequest
@end

@interface OAIImmediatePaymentRequest : OAIObject


@property(nonatomic) OAIImmediatePaymentRequestData* data;

@property(nonatomic) OAIMeta* meta;

@end
