#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIInstoreCustomerTermsandconditionsAcceptanceData
@end

@interface OAIInstoreCustomerTermsandconditionsAcceptanceData : OAIObject

/* The type of Ts and Cs that the shopper/customer has agreed to. 
 */
@property(nonatomic) NSString* type;
/* The current version of the Ts and Cs that the shopper/customer has agreed to. 
 */
@property(nonatomic) NSString* version;

@end
