#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIImportPaymentInstrumentsResponseCreditCards
@end

@interface OAIImportPaymentInstrumentsResponseCreditCards : OAIObject

/* WebPay reference in the transaction logs. This number uniquely identifies the transaction in WebPay. 
 */
@property(nonatomic) NSString* transactionRef;
/* The WebPay transaction timestamp. The timestamp format is ISO8601. 
 */
@property(nonatomic) NSString* transactionTimestamp;
/* The WebPay transaction type. 
 */
@property(nonatomic) NSString* transactionType;
/* The WebPay transaction response code. 
 */
@property(nonatomic) NSString* transactionResponseCode;
/* The WebPay transaction response text. 
 */
@property(nonatomic) NSString* transactionResponseText;
/* The merchant order number used in the WebPay transaction. 
 */
@property(nonatomic) NSString* orderNumber;
/* The bin (first 6 digits) of the credit card number used in the WebPay transaction. 
 */
@property(nonatomic) NSString* bin;
/* The suffix (last 4 digits) of the credit card number used in the WebPay transaction. 
 */
@property(nonatomic) NSString* cardSuffix;
/* The month of the expiry date of the credit card. 
 */
@property(nonatomic) NSString* expiryMonth;
/* The year of the expiry date of the credit card. 
 */
@property(nonatomic) NSString* expiryYear;
/* The amount of the WebPay transaction. 
 */
@property(nonatomic) NSNumber* amount;
/* The import process result for the credit card instrument. 
 */
@property(nonatomic) NSString* result;
/* The import process error message if \"result\" is \"ERROR\". Will be null if \"result\" is not \"ERROR\". 
 */
@property(nonatomic) NSObject* errorMessage;

@end
