#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIDynamicPayload.h"
@protocol OAIDynamicPayload;
@class OAIDynamicPayload;



@protocol OAIInstoreMerchantPaymentSessionPaymentSessionIdData
@end

@interface OAIInstoreMerchantPaymentSessionPaymentSessionIdData : OAIObject


@property(nonatomic) OAIDynamicPayload* merchantInfo;
/* The ID of the associated payment request [optional]
 */
@property(nonatomic) NSString* paymentRequestId;

@end
