#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIGiftingProductDetail.h"
#import "OAIMeta.h"
@protocol OAIGiftingProductDetail;
@class OAIGiftingProductDetail;
@protocol OAIMeta;
@class OAIMeta;



@protocol OAIInlineResponse2001
@end

@interface OAIInlineResponse2001 : OAIObject


@property(nonatomic) OAIGiftingProductDetail* data;

@property(nonatomic) OAIMeta* meta;

@end
