#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIGiftingProductOrderItem.h"
@protocol OAIGiftingProductOrderItem;
@class OAIGiftingProductOrderItem;



@protocol OAIInlineObject
@end

@interface OAIInlineObject : OAIObject

/* Gift cards to be included in the order.  Currently only supports a single entry.  Array is for future roadmap 
 */
@property(nonatomic) NSArray<OAIGiftingProductOrderItem>* orderItems;

@end
