#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIInstoreCustomerInstrumentsData
@end

@interface OAIInstoreCustomerInstrumentsData : OAIObject

/* The unique reference for this interaction as defined by the client application 
 */
@property(nonatomic) NSString* clientReference;

@end
