#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIImmediatePaymentRequestDataPayments
@end

@interface OAIImmediatePaymentRequestDataPayments : OAIObject

/* The payment instrument id from the card capture iframe response or the list payment instruments response. This property can be omitted if the payment token property is present. 
 */
@property(nonatomic) NSString* paymentInstrumentId;
/* The amount you want to pay with the payment instrument. 
 */
@property(nonatomic) NSNumber* amount;

@end
