#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIInstoreMerchantSchemaData
@end

@interface OAIInstoreMerchantSchemaData : OAIObject

/* An arbitrary block of JSON formatted according to JSON Schema standards that can be used for configurable payload validation of merchant payloads 
 */
@property(nonatomic) NSDictionary<NSString*, NSObject*>* schema;
/* The type of the schema e.g. pos or merchant 
 */
@property(nonatomic) NSString* type;
/* A description of the provided schema [optional]
 */
@property(nonatomic) NSString* _description;

@end
