#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIInstrumentAllocationTransactions
@end

@interface OAIInstrumentAllocationTransactions : OAIObject

/* The type of transaction: PAYMENT or REFUND [optional]
 */
@property(nonatomic) NSString* type;
/* Date/time stamp of when the transaction occurred in ISO string format [optional]
 */
@property(nonatomic) NSDate* executionTime;
/* The reference for the payment.  If a refund this is the reference to the transaction being refunded [optional]
 */
@property(nonatomic) NSString* paymentTransactionRef;
/* The reference for the refund. [optional]
 */
@property(nonatomic) NSString* refundTransactionRef;
/* The current status of the transactions [optional]
 */
@property(nonatomic) NSString* status;
/* The amount charged against or refunded to this instrument [optional]
 */
@property(nonatomic) NSNumber* amount;

@end
