#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIInlineResponse2003Data
@end

@interface OAIInlineResponse2003Data : OAIObject

/* Current order status 
 */
@property(nonatomic) NSString* status;
/* Order reference 
 */
@property(nonatomic) NSString* orderId;
/* Quote reference 
 */
@property(nonatomic) NSString* quoteNo;

@end
