#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIImmediatePaymentRequestDataPayments.h"
#import "OAIMerchantPayload.h"
#import "OAIPaymentTransactionType.h"
#import "OAIPosPayload.h"
@protocol OAIImmediatePaymentRequestDataPayments;
@class OAIImmediatePaymentRequestDataPayments;
@protocol OAIMerchantPayload;
@class OAIMerchantPayload;
@protocol OAIPaymentTransactionType;
@class OAIPaymentTransactionType;
@protocol OAIPosPayload;
@class OAIPosPayload;



@protocol OAIImmediatePaymentRequestData
@end

@interface OAIImmediatePaymentRequestData : OAIObject

/* A merchant application specific reference number. This number should uniquely identify the transaction in the merchant’s system. 
 */
@property(nonatomic) NSString* clientReference;
/* The merchant order number of the transaction. 
 */
@property(nonatomic) NSString* orderNumber;
/* An optional flag allowing the consumer to indicate that automatic rollback step should be skipped in the case of failure [optional]
 */
@property(nonatomic) NSNumber* skipRollback;
/* An optional flag allowing the consumer to indicate that a partial success will not trigger a failure and rollback [optional]
 */
@property(nonatomic) NSNumber* allowPartialSuccess;

@property(nonatomic) NSArray<OAIImmediatePaymentRequestDataPayments>* payments;

@property(nonatomic) OAIPosPayload* posPayload;

@property(nonatomic) OAIMerchantPayload* merchantPayload;

@property(nonatomic) OAIPaymentTransactionType* transactionType;

@end
