#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIInlineResponse2002Data.h"
#import "OAIMeta.h"
@protocol OAIInlineResponse2002Data;
@class OAIInlineResponse2002Data;
@protocol OAIMeta;
@class OAIMeta;



@protocol OAIInlineResponse2002
@end

@interface OAIInlineResponse2002 : OAIObject


@property(nonatomic) OAIInlineResponse2002Data* data;

@property(nonatomic) OAIMeta* meta;

@end
