#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAITransactionType.h"
@protocol OAITransactionType;
@class OAITransactionType;



@protocol OAIInstoreMerchantPaymentsAgreementsPaymentTokenData
@end

@interface OAIInstoreMerchantPaymentsAgreementsPaymentTokenData : OAIObject

/* The payment token of the payment agreement. The payment token is a unique identifier for the payment agreement 
 */
@property(nonatomic) NSString* paymentToken;

@property(nonatomic) NSNumber* amount;
/* A merchant application specific reference number for the transaction. 
 */
@property(nonatomic) NSString* clientReference;
/* A merchant order number for the transaction. 
 */
@property(nonatomic) NSString* orderNumber;

@property(nonatomic) OAITransactionType* transactionType;
/* A merchant application specific reference number for the customer. [optional]
 */
@property(nonatomic) NSString* customerRef;

@end
