#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIInitiatePaymentInstrumentAdditionResultsData
@end

@interface OAIInitiatePaymentInstrumentAdditionResultsData : OAIObject

/* The URL of an iframe. This iframe is used to capture a credit card number, expiry and CVV 
 */
@property(nonatomic) NSString* cardCaptureURL;
/* Container reference in the transaction logs. This number uniquely identifies the transaction in the container [optional]
 */
@property(nonatomic) NSString* transactionRef;

@end
