#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Village Wallet
* APIs for Village Wallet
*
* The version of the OpenAPI document: 0.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIMerchantTransactionsTransactionIdRefundData
@end

@interface OAIMerchantTransactionsTransactionIdRefundData : OAIObject

/* The reason for the refund, or other message logged with the transaction 
 */
@property(nonatomic) NSString* reason;
/* An optional client reference to be associated with the transaction.  If not suplied the transactionId will be used. [optional]
 */
@property(nonatomic) NSString* clientReference;

@end
