#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIInstoreMerchantPaymentsAgreementsPaymentTokenData.h"
#import "OAIMeta.h"
@protocol OAIInstoreMerchantPaymentsAgreementsPaymentTokenData;
@class OAIInstoreMerchantPaymentsAgreementsPaymentTokenData;
@protocol OAIMeta;
@class OAIMeta;



@protocol OAIMerchantChargePaymentAgreementRequest
@end

@interface OAIMerchantChargePaymentAgreementRequest : OAIObject


@property(nonatomic) OAIInstoreMerchantPaymentsAgreementsPaymentTokenData* data;

@property(nonatomic) OAIMeta* meta;

@end
