#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIMerchantSchemaDetailsResultData.h"
#import "OAIMeta.h"
@protocol OAIMerchantSchemaDetailsResultData;
@class OAIMerchantSchemaDetailsResultData;
@protocol OAIMeta;
@class OAIMeta;



@protocol OAIMerchantSchemaDetailsResult
@end

@interface OAIMerchantSchemaDetailsResult : OAIObject


@property(nonatomic) OAIMerchantSchemaDetailsResultData* data;

@property(nonatomic) OAIMeta* meta;

@end
