#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Village Wallet
* APIs for Village Wallet
*
* The version of the OpenAPI document: 0.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIMerchantTransactionSummaryAllOf
@end

@interface OAIMerchantTransactionSummaryAllOf : OAIObject

/* The ID of the wallet associated with this transaction 
 */
@property(nonatomic) NSString* walletId;

@end
