#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIMerchantProfileResponseAllowedPaymentMethodsPaymentAgreement
@end

@interface OAIMerchantProfileResponseAllowedPaymentMethodsPaymentAgreement : OAIObject

/* The allowed instrument types that can be used as the funding source of a payment agreement. 
 */
@property(nonatomic) NSArray<NSString*>* allowedInstrumentTypes;
/* This property indicates the status of the payment agreement service in the container. 
 */
@property(nonatomic) NSString* serviceStatus;

@end
