#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIInstoreMerchantPaymentsData.h"
#import "OAIMeta.h"
@protocol OAIInstoreMerchantPaymentsData;
@class OAIInstoreMerchantPaymentsData;
@protocol OAIMeta;
@class OAIMeta;



@protocol OAIMerchantPaymentRequest
@end

@interface OAIMerchantPaymentRequest : OAIObject


@property(nonatomic) OAIInstoreMerchantPaymentsData* data;

@property(nonatomic) OAIMeta* meta;

@end
