#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIMerchantProfileResponseAllowedPaymentMethodsGooglePayDebitCard
@end

@interface OAIMerchantProfileResponseAllowedPaymentMethodsGooglePayDebitCard : OAIObject

/* The allowed networks (schemes) for debit card transactions. 
 */
@property(nonatomic) NSArray<NSString*>* allowedNetworks;
/* The allowed transaction types for debit card transactions. 
 */
@property(nonatomic) NSArray<NSString*>* allowedTransactionTypes;

@end
