#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Village Wallet
* APIs for Village Wallet
*
* The version of the OpenAPI document: 0.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIMerchantSchemaSummary
@end

@interface OAIMerchantSchemaSummary : OAIObject

/* The unique ID assigned to the newly created schema 
 */
@property(nonatomic) NSString* schemaId;
/* The type of the schema e.g. pos, merchant 
 */
@property(nonatomic) NSString* type;
/* A description for the schema [optional]
 */
@property(nonatomic) NSString* _description;

@end
