#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIMerchantProfileResponseAllowedPaymentMethodsGooglePayCreditCard.h"
#import "OAIMerchantProfileResponseAllowedPaymentMethodsGooglePayDebitCard.h"
@protocol OAIMerchantProfileResponseAllowedPaymentMethodsGooglePayCreditCard;
@class OAIMerchantProfileResponseAllowedPaymentMethodsGooglePayCreditCard;
@protocol OAIMerchantProfileResponseAllowedPaymentMethodsGooglePayDebitCard;
@class OAIMerchantProfileResponseAllowedPaymentMethodsGooglePayDebitCard;



@protocol OAIMerchantProfileResponseAllowedPaymentMethodsApplePay
@end

@interface OAIMerchantProfileResponseAllowedPaymentMethodsApplePay : OAIObject


@property(nonatomic) OAIMerchantProfileResponseAllowedPaymentMethodsGooglePayCreditCard* creditCard;

@property(nonatomic) OAIMerchantProfileResponseAllowedPaymentMethodsGooglePayDebitCard* debitCard;
/* This property indicates the status of the apple pay service in the container. 
 */
@property(nonatomic) NSString* serviceStatus;

@end
