#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Village Wallet
* APIs for Village Wallet
*
* The version of the OpenAPI document: 0.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIDynamicPayload.h"
@protocol OAIDynamicPayload;
@class OAIDynamicPayload;



@protocol OAIMerchantPaymentSessionPaymentSessionIdData
@end

@interface OAIMerchantPaymentSessionPaymentSessionIdData : OAIObject


@property(nonatomic) OAIDynamicPayload* merchantInfo;
/* The ID of the associated payment request [optional]
 */
@property(nonatomic) NSString* paymentRequestId;

@end
