#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIOpenpayPaymentsRequestStoreData
@end

@interface OAIOpenpayPaymentsRequestStoreData : OAIObject

/* The payment transaction store id. 
 */
@property(nonatomic) NSString* storeId;
/* A pin for the payment method id. [optional]
 */
@property(nonatomic) NSString* pin;

@end
