#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIOpenpayPaymentsRequestPayments
@end

@interface OAIOpenpayPaymentsRequestPayments : OAIObject

/* The payment token. 
 */
@property(nonatomic) NSString* paymentToken;
/* The amount you want to pay with the payment instrument. 
 */
@property(nonatomic) NSNumber* amount;
/* The GST amount of the full amount you want to pay with the payment instrument. [optional]
 */
@property(nonatomic) NSNumber* gstAmount;

@end
