#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIOpenpayPaymentsRequestTransactionType
@end

@interface OAIOpenpayPaymentsRequestTransactionType : OAIObject

/* The container transaction type to use for openpay instruments. [optional]
 */
@property(nonatomic) NSString* openPay;

@end
