#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIOpenpayPaymentsRequestPayments.h"
#import "OAIOpenpayPaymentsRequestStoreData.h"
#import "OAIOpenpayPaymentsRequestTransactionType.h"
@protocol OAIOpenpayPaymentsRequestPayments;
@class OAIOpenpayPaymentsRequestPayments;
@protocol OAIOpenpayPaymentsRequestStoreData;
@class OAIOpenpayPaymentsRequestStoreData;
@protocol OAIOpenpayPaymentsRequestTransactionType;
@class OAIOpenpayPaymentsRequestTransactionType;



@protocol OAIOpenpayPaymentsRequest
@end

@interface OAIOpenpayPaymentsRequest : OAIObject


@property(nonatomic) OAIOpenpayPaymentsRequestTransactionType* transactionType;
/* A merchant application specific reference number. This number should uniquely identify the transaction in the merchant’s system. 
 */
@property(nonatomic) NSString* clientReference;
/* A merchant application specific reference number. This number should uniquely identify the customer in the merchant’s system. [optional]
 */
@property(nonatomic) NSString* customerRef;
/* The merchant order number of the transaction. 
 */
@property(nonatomic) NSString* orderNumber;
/* The customer purchase order number of the transaction. [optional]
 */
@property(nonatomic) NSString* customerPurchaseOrder;
/* The channel from which this charge is originating, eg. Online, In-Store. 
 */
@property(nonatomic) NSString* channel;
/* The unique identifier for the merchants trading account. [optional]
 */
@property(nonatomic) NSString* tradingAccountId;
/* The merchants transaction date and time. The timestamp format is ISO8601. [optional]
 */
@property(nonatomic) NSString* merchantTransactedAt;

@property(nonatomic) NSArray<OAIOpenpayPaymentsRequestPayments>* payments;

@property(nonatomic) OAIOpenpayPaymentsRequestStoreData* storeData;

@end
