#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIPaymentsSuccessResponseStepUp1.h"
@protocol OAIPaymentsSuccessResponseStepUp1;
@class OAIPaymentsSuccessResponseStepUp1;



@protocol OAIPaymentsErrorResponseApplePay
@end

@interface OAIPaymentsErrorResponseApplePay : OAIObject

/* The apple pay payment instrument id. 
 */
@property(nonatomic) NSString* paymentInstrumentId;
/* The apple pay payment token. The payment token is a unique identifier for the payment instrument. 
 */
@property(nonatomic) NSString* paymentToken;
/* The error code. Only present if an error occurred during payment. 
 */
@property(nonatomic) NSString* errorCode;
/* The error message. Only present if an error occurred during payment. 
 */
@property(nonatomic) NSString* errorMessage;
/* The error detail. Only present if an error occurred during payment. 
 */
@property(nonatomic) NSString* errorDetail;

@property(nonatomic) OAIPaymentsSuccessResponseStepUp1* stepUp;
/* The external service code (from eg. Apple Pay). This property is only included in the response if it is enabled in the consumers API configuration. [optional]
 */
@property(nonatomic) NSString* externalServiceCode;
/* The external service message (from eg. Apple Pay). This property is only included in the response if it is enabled in the consumers API configuration. [optional]
 */
@property(nonatomic) NSString* externalServiceMessage;

@end
