#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIPaymentsRequestStoreData
@end

@interface OAIPaymentsRequestStoreData : OAIObject

/* The in-store payment transaction store id. 
 */
@property(nonatomic) NSString* storeId;
/* The in-store payment transaction store id. This is a 12 digit \"0\" [zero] padded numeric string. 
 */
@property(nonatomic) NSString* rrn;
/* The in-store payment transaction timestamp. The timestamp format is milliseconds since epoch. 
 */
@property(nonatomic) NSNumber* transactionTimestamp;

@end
