#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIPaymentsSuccessResponseThreeDS
@end

@interface OAIPaymentsSuccessResponseThreeDS : OAIObject

/* Received in response to a Visa authenticated Purchase and PreAuth. Only present for Visa. 
 */
@property(nonatomic) NSString* car;
/* The Directory Server (DS) authentication identification code. A universally unique transaction identifier assigned by the DS to identify a single transaction. The format of the value is defined in IETF RFC 4122. It may utilise any of the specified versions if the output meets specific requirements. 
 */
@property(nonatomic) NSString* dsTransID;
/* The SLI from the the schemes. 
 */
@property(nonatomic) NSString* sli;

@end
