#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIPaymentsRequestBasketData
@end

@interface OAIPaymentsRequestBasketData : OAIObject

/* The item id, article id or SKU. Required if 'category' is not present. 
 */
@property(nonatomic) NSString* itemId;
/* The items category code. Required if 'itemId' is not present or, if 'subcategory' is present. 
 */
@property(nonatomic) NSString* category;
/* The items subcategory code. Requires 'category' to be present. 
 */
@property(nonatomic) NSString* subcategory;
/* The item, category or subcategory description. [optional]
 */
@property(nonatomic) NSString* _description;
/* The item quantity. [optional]
 */
@property(nonatomic) NSNumber* quantity;
/* The item price. [optional]
 */
@property(nonatomic) NSNumber* price;
/* The country currency code. [optional]
 */
@property(nonatomic) NSString* currency;

@end
