#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIPaymentsSuccessResponseApplePay.h"
#import "OAIPaymentsSuccessResponseCreditCards.h"
#import "OAIPaymentsSuccessResponseFraudResponse.h"
#import "OAIPaymentsSuccessResponseGiftCards.h"
#import "OAIPaymentsSuccessResponseGooglePay.h"
#import "OAIPaymentsSuccessResponsePayPal.h"
#import "OAIPaymentsSuccessResponseUnknown.h"
@protocol OAIPaymentsSuccessResponseApplePay;
@class OAIPaymentsSuccessResponseApplePay;
@protocol OAIPaymentsSuccessResponseCreditCards;
@class OAIPaymentsSuccessResponseCreditCards;
@protocol OAIPaymentsSuccessResponseFraudResponse;
@class OAIPaymentsSuccessResponseFraudResponse;
@protocol OAIPaymentsSuccessResponseGiftCards;
@class OAIPaymentsSuccessResponseGiftCards;
@protocol OAIPaymentsSuccessResponseGooglePay;
@class OAIPaymentsSuccessResponseGooglePay;
@protocol OAIPaymentsSuccessResponsePayPal;
@class OAIPaymentsSuccessResponsePayPal;
@protocol OAIPaymentsSuccessResponseUnknown;
@class OAIPaymentsSuccessResponseUnknown;



@protocol OAIPaymentsSuccessResponse
@end

@interface OAIPaymentsSuccessResponse : OAIObject

/* Container reference in the transaction logs. This number uniquely identifies the whole/grouped transaction in the container. 
 */
@property(nonatomic) NSString* transactionReceipt;
/* A flag to indicate if a split payment was only partially successful, ie. at least 1 of the payment instruments had a successful payment result. 
 */
@property(nonatomic) NSNumber* partialSuccess;

@property(nonatomic) OAIPaymentsSuccessResponseFraudResponse* fraudResponse;

@property(nonatomic) NSArray<OAIPaymentsSuccessResponseCreditCards>* creditCards;

@property(nonatomic) NSArray<OAIPaymentsSuccessResponseGiftCards>* giftCards;

@property(nonatomic) NSArray<OAIPaymentsSuccessResponsePayPal>* payPal;
/* Android Pay has been replaced by Google Pay. This property has been retained for backward compatibility and will always be an empty array. 
 */
@property(nonatomic) NSArray<NSObject*>* androidPay;

@property(nonatomic) NSArray<OAIPaymentsSuccessResponseGooglePay>* googlePay;

@property(nonatomic) NSArray<OAIPaymentsSuccessResponseApplePay>* applePay;

@property(nonatomic) NSArray<OAIPaymentsSuccessResponseUnknown>* unknown;

@end
