#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIPaymentsRequestExtendedMerchantData.h"
#import "OAIPaymentsRequestFraudPayload.h"
#import "OAIPaymentsRequestPayments.h"
#import "OAIPaymentsRequestShippingAddress.h"
#import "OAIPaymentsRequestStoreData.h"
#import "OAIPaymentsRequestTransactionType.h"
@protocol OAIPaymentsRequestExtendedMerchantData;
@class OAIPaymentsRequestExtendedMerchantData;
@protocol OAIPaymentsRequestFraudPayload;
@class OAIPaymentsRequestFraudPayload;
@protocol OAIPaymentsRequestPayments;
@class OAIPaymentsRequestPayments;
@protocol OAIPaymentsRequestShippingAddress;
@class OAIPaymentsRequestShippingAddress;
@protocol OAIPaymentsRequestStoreData;
@class OAIPaymentsRequestStoreData;
@protocol OAIPaymentsRequestTransactionType;
@class OAIPaymentsRequestTransactionType;



@protocol OAIPaymentsRequest
@end

@interface OAIPaymentsRequest : OAIObject


@property(nonatomic) OAIPaymentsRequestTransactionType* transactionType;
/* A merchant application specific reference number. This number should uniquely identify the transaction in the merchant’s system. 
 */
@property(nonatomic) NSString* clientReference;
/* The merchant order number of the transaction. 
 */
@property(nonatomic) NSString* orderNumber;

@property(nonatomic) OAIPaymentsRequestShippingAddress* shippingAddress;

@property(nonatomic) NSArray<OAIPaymentsRequestPayments>* payments;
/* This object is only required if the payments request contains paypal instruments. [optional]
 */
@property(nonatomic) NSArray<OAIPaymentsRequestExtendedMerchantData>* extendedMerchantData;

@property(nonatomic) OAIPaymentsRequestStoreData* storeData;

@property(nonatomic) OAIPaymentsRequestFraudPayload* fraudPayload;

@end
