#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIPaymentsRequestPayments
@end

@interface OAIPaymentsRequestPayments : OAIObject

/* The payment instrument id from the card capture iframe response or the list payment instruments response. This property can be omitted if the payment token property is present. 
 */
@property(nonatomic) NSString* paymentInstrumentId;
/* The payment token from the card capture iframe response or the list payment instruments response. This property can be omitted if the payment instrument id property is present. 
 */
@property(nonatomic) NSString* paymentToken;
/* The amount you want to pay with the payment instrument. 
 */
@property(nonatomic) NSNumber* amount;
/* The step-up token is used to track additional credit card information (eg. CVV and expiry) attached to the payment instrument. It's only valid for a predefined time and if an expired step-up token is used during payment, the payment for that instrument will fail and the user will have to get a new step-up token before retrying the payment. A step-up token is returned in the response of a credit card iframe. This property is currently only required for credit card instruments and only if specific credit card information (eg. CVV and expiry) is required during payment. [optional]
 */
@property(nonatomic) NSString* stepUpToken;
/* The passcode is used to send additional information (eg. gift card PIN) for the payment instrument. This property is currently only required for gift card instruments and only if the gift card PIN is required during payment. This property should NOT be used with credit card instruments (see stepUpToken). [optional]
 */
@property(nonatomic) NSString* passcode;

@end
