#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIPaymentsSuccessResponseExtendedTransactionData
@end

@interface OAIPaymentsSuccessResponseExtendedTransactionData : OAIObject

/* The name of the extended transaction data field. The 'token' field is only included in the response if it is enabled in the consumers API configuration. 
 */
@property(nonatomic) NSString* field;
/* The value of the extended transaction data field. 
 */
@property(nonatomic) NSString* value;

@end
