#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIPaymentsRPVSErrorResponseValidationErrors.h"
@protocol OAIPaymentsRPVSErrorResponseValidationErrors;
@class OAIPaymentsRPVSErrorResponseValidationErrors;



@protocol OAIPaymentsRPVSErrorResponseBasketData
@end

@interface OAIPaymentsRPVSErrorResponseBasketData : OAIObject

/* The item id, article id or SKU. Present if 'itemId' was sent in the basket data of the payments request. 
 */
@property(nonatomic) NSString* itemId;
/* The items category code. Present if 'category' was sent in the basket data of the payments request. 
 */
@property(nonatomic) NSString* category;
/* The items subcategory code. Present if 'subcategory' was sent in the basket data of the payments request. 
 */
@property(nonatomic) NSString* subcategory;
/* This array contains the details of the restricted product validation (RPVS) errors. 
 */
@property(nonatomic) NSArray<OAIPaymentsRPVSErrorResponseValidationErrors>* validationErrors;

@end
