#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIPaymentsSuccessResponseReceiptData1
@end

@interface OAIPaymentsSuccessResponseReceiptData1 : OAIObject

/* The suffix (last 4 digits) of the gift card number used in the WEX transaction. 
 */
@property(nonatomic) NSString* cardSuffix;

@end
