#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIPaymentsRPVSErrorResponseApplePay.h"
#import "OAIPaymentsRPVSErrorResponseCreditCards.h"
#import "OAIPaymentsRPVSErrorResponseGiftCards.h"
#import "OAIPaymentsRPVSErrorResponseGooglePay.h"
#import "OAIPaymentsRPVSErrorResponsePayPal.h"
@protocol OAIPaymentsRPVSErrorResponseApplePay;
@class OAIPaymentsRPVSErrorResponseApplePay;
@protocol OAIPaymentsRPVSErrorResponseCreditCards;
@class OAIPaymentsRPVSErrorResponseCreditCards;
@protocol OAIPaymentsRPVSErrorResponseGiftCards;
@class OAIPaymentsRPVSErrorResponseGiftCards;
@protocol OAIPaymentsRPVSErrorResponseGooglePay;
@class OAIPaymentsRPVSErrorResponseGooglePay;
@protocol OAIPaymentsRPVSErrorResponsePayPal;
@class OAIPaymentsRPVSErrorResponsePayPal;



@protocol OAIPaymentsRPVSErrorResponse
@end

@interface OAIPaymentsRPVSErrorResponse : OAIObject

/* The http status code (403). 
 */
@property(nonatomic) NSNumber* httpStatusCode;
/* The error code. 
 */
@property(nonatomic) NSString* errorCode;
/* The error message. 
 */
@property(nonatomic) NSString* errorMessage;
/* The error detail. 
 */
@property(nonatomic) NSString* errorDetail;

@property(nonatomic) NSArray<OAIPaymentsRPVSErrorResponseCreditCards>* creditCards;

@property(nonatomic) NSArray<OAIPaymentsRPVSErrorResponseGiftCards>* giftCards;

@property(nonatomic) NSArray<OAIPaymentsRPVSErrorResponsePayPal>* payPal;

@property(nonatomic) NSArray<OAIPaymentsRPVSErrorResponseGooglePay>* googlePay;

@property(nonatomic) NSArray<OAIPaymentsRPVSErrorResponseApplePay>* applePay;

@end
