#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Village Wallet
* APIs for Village Wallet
*
* The version of the OpenAPI document: 0.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIQr
@end

@interface OAIQr : OAIObject

/* The ID of the QR code 
 */
@property(nonatomic) NSString* qrId;
/* The ID of the payment request linked to this QR code 
 */
@property(nonatomic) NSString* referenceId;
/* The type of ID held in referenceId 
 */
@property(nonatomic) NSString* referenceType;
/* The text content for the QR code 
 */
@property(nonatomic) NSString* content;
/* Base64 encoded PNG of the QR Code 
 */
@property(nonatomic) NSString* image;
/* ISO date/time string indicating when the QR code will expire and become ineffective.  If absent then the QR code will not expire until it is deleted [optional]
 */
@property(nonatomic) NSDate* expiryTime;

@end
