#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIRefundsRequestStoreData
@end

@interface OAIRefundsRequestStoreData : OAIObject

/* The refund transaction merchant group id. The group id is defined as a logical grouping of merchants or stores. A default configured group id is set in Apigee if absent in the payload. [optional]
 */
@property(nonatomic) NSString* groupId;
/* The in-store refund transaction terminal id. This is a 8 character alphanumeric string. If present in the payload the 'storeId' has to be omitted. 
 */
@property(nonatomic) NSString* terminalId;
/* The in-store refund transaction store id. If present in the payload the 'terminalId' and 'stan' can be omitted. 
 */
@property(nonatomic) NSString* storeId;
/* The in-store refund transaction lane id. [optional]
 */
@property(nonatomic) NSString* laneId;
/* The System Trace Audit Number (STAN) used to identify the transaction. This is a 6 digit numeric string. 
 */
@property(nonatomic) NSString* stan;
/* The in-store refund transaction store id. This is a 12 digit \"0\" [zero] padded numeric string. 
 */
@property(nonatomic) NSString* rrn;
/* The in-store refund transaction timestamp. The timestamp format is milliseconds since epoch. 
 */
@property(nonatomic) NSNumber* transactionTimestamp;

@end
