#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAITokenizeAndroidPayRequest
@end

@interface OAITokenizeAndroidPayRequest : OAIObject

/* The \"encryptedMessage\" value from the Android Pay wallet. 
 */
@property(nonatomic) NSString* encryptedMessage;
/* The \"ephemeralPublicKey\" value from the Android Pay wallet. 
 */
@property(nonatomic) NSString* ephemeralPublicKey;
/* The \"tag\" value from the Android Pay wallet. 
 */
@property(nonatomic) NSString* tag;
/* The \"publicKeyHash\" value from the merchant profile response. 
 */
@property(nonatomic) NSString* publicKeyHash;
/* The type/schema value from the Android Pay wallet. 
 */
@property(nonatomic) NSString* instrumentType;
/* A flag to indicate if this payment instrument has to be set as the primary instrument. 
 */
@property(nonatomic) NSNumber* primary;
/* The display text returned by the Android Pay wallet. 
 */
@property(nonatomic) NSString* comment;

@end
