#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAITokenizeGiftcardRequest
@end

@interface OAITokenizeGiftcardRequest : OAIObject

/* The gift card number. 
 */
@property(nonatomic) NSString* cardNumber;
/* The gift card pin code. 
 */
@property(nonatomic) NSString* pinCode;
/* A flag to indicate if this payment instrument has to be set as the primary instrument. 
 */
@property(nonatomic) NSNumber* primary;
/* A flag to indicate if this payment instrument has to be saved in the container or tokenized for one-off use. 
 */
@property(nonatomic) NSNumber* save;

@end
