#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIInstoreMerchantPaymentSessionPaymentSessionIdData.h"
#import "OAIMeta.h"
@protocol OAIInstoreMerchantPaymentSessionPaymentSessionIdData;
@class OAIInstoreMerchantPaymentSessionPaymentSessionIdData;
@protocol OAIMeta;
@class OAIMeta;



@protocol OAIUpdatePaymentSessionRequest1
@end

@interface OAIUpdatePaymentSessionRequest1 : OAIObject


@property(nonatomic) OAIInstoreMerchantPaymentSessionPaymentSessionIdData* data;

@property(nonatomic) OAIMeta* meta;

@end
