#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIVerifyPaymentInstrumentsRequestFraudPayload.h"
#import "OAIVerifyPaymentInstrumentsRequestPaymentInstruments.h"
@protocol OAIVerifyPaymentInstrumentsRequestFraudPayload;
@class OAIVerifyPaymentInstrumentsRequestFraudPayload;
@protocol OAIVerifyPaymentInstrumentsRequestPaymentInstruments;
@class OAIVerifyPaymentInstrumentsRequestPaymentInstruments;



@protocol OAIVerifyPaymentInstrumentsRequest
@end

@interface OAIVerifyPaymentInstrumentsRequest : OAIObject

/* A merchant application specific reference number. This number should uniquely identify the transaction in the merchant’s system. 
 */
@property(nonatomic) NSString* clientReference;

@property(nonatomic) NSArray<OAIVerifyPaymentInstrumentsRequestPaymentInstruments>* paymentInstruments;

@property(nonatomic) OAIVerifyPaymentInstrumentsRequestFraudPayload* fraudPayload;

@end
