#import <Foundation/Foundation.h>
#import "OAICustomerCreatePaymentAgreementRequest.h"
#import "OAICustomerPaymentAgreementResponse.h"
#import "OAICustomerPaymentDetails.h"
#import "OAICustomerPaymentSessionResult.h"
#import "OAICustomerPreferences.h"
#import "OAICustomerPreferencesResult.h"
#import "OAICustomerTermsAndConditions.h"
#import "OAICustomerTermsAndConditionsResult.h"
#import "OAICustomerUpdatePaymentAgreementRequest.h"
#import "OAIError.h"
#import "OAIGetCustomerPaymentInstrumentResult.h"
#import "OAIGetCustomerPaymentInstrumentsResults.h"
#import "OAIGetCustomerPaymentRequestResult.h"
#import "OAIGetCustomerTransactionDetailsResults.h"
#import "OAIGetCustomerTransactionsResult.h"
#import "OAIInitiatePaymentInstrumentAdditionResults.h"
#import "OAIInstrumentAdditionDetails.h"
#import "OAIMakeCustomerPaymentResults.h"
#import "OAIPaymentAgreementListResponse.h"
#import "OAIUpdatePaymentSessionRequest.h"
#import "OAIApi.h"

/**
* Wpay APIs
* Wpay APIs for payments and gifting
*
* The version of the OpenAPI document: 1.0.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAICustomerApi: NSObject <OAIApi>

extern NSString* kOAICustomerApiErrorDomain;
extern NSInteger kOAICustomerApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Agree to T&Cs
/// Customer accepts terms and conditions
///
/// @param xWalletID 
/// @param customerTermsAndConditions 
/// 
///  code:204 message:"Ts and Cs successfully accepted.  No content returned"
///
/// @return void
-(NSURLSessionTask*) acceptCustomerTermsAndConditionsWithXWalletID: (NSString*) xWalletID
    customerTermsAndConditions: (OAICustomerTermsAndConditions*) customerTermsAndConditions
    completionHandler: (void (^)(NSError* error)) handler;


/// Create Payment Agreement
/// Create an new payment agreement
///
/// @param xWalletID 
/// @param customerCreatePaymentAgreementRequest 
/// 
///  code:200 message:"Response for Get, Create and Update Payment Agreements"
///
/// @return OAICustomerPaymentAgreementResponse*
-(NSURLSessionTask*) createCustomerPaymentAgreementWithXWalletID: (NSString*) xWalletID
    customerCreatePaymentAgreementRequest: (OAICustomerCreatePaymentAgreementRequest*) customerCreatePaymentAgreementRequest
    completionHandler: (void (^)(OAICustomerPaymentAgreementResponse* output, NSError* error)) handler;


/// Update Payment Session
/// Update the payment session details
///
/// @param xApiKey The API key for the request. The API keys (non-prod/prod) will be supplied by the Digital Pay team.
/// @param authorization The Bearer token for the request. The Bearer token authentication approach can be used by API consumers that implement a client-to-server architecture (mobile app, browser site/page) or server-to-server architecture (BFF, microservice, web server, etc.) for calling Digital Pay APIs. However the Bearer token for a shopper/customer must be obtained from the IDM Server Token API which can only be accessed from a server-to-server architecture (BFF, microservice, web server, etc.). The Authorization header is only required if the X-JWS-Signature header is not present.
/// @param xJWSSignature The JWS signature used to sign the request. The JWS signature authentication approach can only be used by API consumers that implement a server-to-server architecture (BFF, microservice, web server, etc.) for calling the Digital Pay APIs. The RSA private key, required to generate the signiture, has to be stored securely and should not be publicly accessible. The X-JWS-Signature header is only required if the Authorization header is not present.
/// @param paymentSessionId The ID of the specific payment session to retrieve
/// @param updatePaymentSessionRequest 
/// @param xAuthKey (Deprecated) You are required to use this header to provide the base64 encoded API key. Requires the X-Auth-Digest header to be present. (optional)
/// @param xAuthDigest (Deprecated) You are required to use this header to provide the encrypted API key. The value is the API key encrypted with the client secret key. Requires the X-Auth-Key header to be present. (optional)
/// @param xMessageId This id is used to keep track of the request and its response in the Digital Pay platform. If no value is provided for the request header, Apigee will auto generate an id to use for the request. This header will also be returned in the response and will have the value passed in (or auto generated) from the request. (optional)
/// 
///  code:204 message:"The payment session has been successfully updated. No content returned.",
///  code:422 message:"The specified Payment Session ID doesn't exist, has already been associated with a wallet or has expired"
///
/// @return void
-(NSURLSessionTask*) customerUpdatePaymentSessionWithXApiKey: (NSString*) xApiKey
    authorization: (NSString*) authorization
    xJWSSignature: (NSString*) xJWSSignature
    paymentSessionId: (NSString*) paymentSessionId
    updatePaymentSessionRequest: (OAIUpdatePaymentSessionRequest*) updatePaymentSessionRequest
    xAuthKey: (NSString*) xAuthKey
    xAuthDigest: (NSString*) xAuthDigest
    xMessageId: (NSString*) xMessageId
    completionHandler: (void (^)(NSError* error)) handler;


/// Delete Payment Session
/// Deletes a payment session by setting its expiration date/time to now
///
/// @param xApiKey The API key for the request. The API keys (non-prod/prod) will be supplied by the Digital Pay team.
/// @param authorization The Bearer token for the request. The Bearer token authentication approach can be used by API consumers that implement a client-to-server architecture (mobile app, browser site/page) or server-to-server architecture (BFF, microservice, web server, etc.) for calling Digital Pay APIs. However the Bearer token for a shopper/customer must be obtained from the IDM Server Token API which can only be accessed from a server-to-server architecture (BFF, microservice, web server, etc.). The Authorization header is only required if the X-JWS-Signature header is not present.
/// @param xJWSSignature The JWS signature used to sign the request. The JWS signature authentication approach can only be used by API consumers that implement a server-to-server architecture (BFF, microservice, web server, etc.) for calling the Digital Pay APIs. The RSA private key, required to generate the signiture, has to be stored securely and should not be publicly accessible. The X-JWS-Signature header is only required if the Authorization header is not present.
/// @param paymentSessionId The ID of the specific payment session to delete
/// @param xAuthKey (Deprecated) You are required to use this header to provide the base64 encoded API key. Requires the X-Auth-Digest header to be present. (optional)
/// @param xAuthDigest (Deprecated) You are required to use this header to provide the encrypted API key. The value is the API key encrypted with the client secret key. Requires the X-Auth-Key header to be present. (optional)
/// @param xMessageId This id is used to keep track of the request and its response in the Digital Pay platform. If no value is provided for the request header, Apigee will auto generate an id to use for the request. This header will also be returned in the response and will have the value passed in (or auto generated) from the request. (optional)
/// 
///  code:204 message:"The payment session has been successfully deleted. No content returned."
///
/// @return void
-(NSURLSessionTask*) deleteCustomerPaymentSessionWithXApiKey: (NSString*) xApiKey
    authorization: (NSString*) authorization
    xJWSSignature: (NSString*) xJWSSignature
    paymentSessionId: (NSString*) paymentSessionId
    xAuthKey: (NSString*) xAuthKey
    xAuthDigest: (NSString*) xAuthDigest
    xMessageId: (NSString*) xMessageId
    completionHandler: (void (^)(NSError* error)) handler;


/// Delete a payment instrument
/// Delete an existing payment instrument
///
/// @param xApiKey The API key for the request. The API keys (non-prod/prod) will be supplied by the Digital Pay team.
/// @param authorization The Bearer token for the request. The Bearer token authentication approach can be used by API consumers that implement a client-to-server architecture (mobile app, browser site/page) or server-to-server architecture (BFF, microservice, web server, etc.) for calling Digital Pay APIs. However the Bearer token for a shopper/customer must be obtained from the IDM Server Token API which can only be accessed from a server-to-server architecture (BFF, microservice, web server, etc.). The Authorization header is only required if the X-JWS-Signature header is not present.
/// @param xJWSSignature The JWS signature used to sign the request. The JWS signature authentication approach can only be used by API consumers that implement a server-to-server architecture (BFF, microservice, web server, etc.) for calling the Digital Pay APIs. The RSA private key, required to generate the signiture, has to be stored securely and should not be publicly accessible. The X-JWS-Signature header is only required if the Authorization header is not present.
/// @param paymentInstrumentId The ID of the specific instrument
/// @param xAuthKey (Deprecated) You are required to use this header to provide the base64 encoded API key. Requires the X-Auth-Digest header to be present. (optional)
/// @param xAuthDigest (Deprecated) You are required to use this header to provide the encrypted API key. The value is the API key encrypted with the client secret key. Requires the X-Auth-Key header to be present. (optional)
/// @param xMessageId This id is used to keep track of the request and its response in the Digital Pay platform. If no value is provided for the request header, Apigee will auto generate an id to use for the request. This header will also be returned in the response and will have the value passed in (or auto generated) from the request. (optional)
/// 
///  code:204 message:"Payment Instrument successfully deleted.  No content returned"
///
/// @return void
-(NSURLSessionTask*) deletePaymentInstrumentWithXApiKey: (NSString*) xApiKey
    authorization: (NSString*) authorization
    xJWSSignature: (NSString*) xJWSSignature
    paymentInstrumentId: (NSString*) paymentInstrumentId
    xAuthKey: (NSString*) xAuthKey
    xAuthDigest: (NSString*) xAuthDigest
    xMessageId: (NSString*) xMessageId
    completionHandler: (void (^)(NSError* error)) handler;


/// Get Payment Instrument
/// Get the specified payment instrument of the customer. Returns the payment instrument data and optionally the sensitive data (encrypted in the response) of an instrument record
///
/// @param paymentInstrumentId The ID of the specific instrument
/// @param xApiKey The API key for the request. The API keys (non-prod/prod) will be supplied by the Digital Pay team.
/// @param authorization The Bearer token for the request. The Bearer token authentication approach can be used by API consumers that implement a client-to-server architecture (mobile app, browser site/page) or server-to-server architecture (BFF, microservice, web server, etc.) for calling Digital Pay APIs. However the Bearer token for a shopper/customer must be obtained from the IDM Server Token API which can only be accessed from a server-to-server architecture (BFF, microservice, web server, etc.). The Authorization header is only required if the X-JWS-Signature header is not present.
/// @param xJWSSignature The JWS signature used to sign the request. The JWS signature authentication approach can only be used by API consumers that implement a server-to-server architecture (BFF, microservice, web server, etc.) for calling the Digital Pay APIs. The RSA private key, required to generate the signiture, has to be stored securely and should not be publicly accessible. The X-JWS-Signature header is only required if the Authorization header is not present.
/// @param xAuthKey (Deprecated) You are required to use this header to provide the base64 encoded API key. Requires the X-Auth-Digest header to be present. (optional)
/// @param xAuthDigest (Deprecated) You are required to use this header to provide the encrypted API key. The value is the API key encrypted with the client secret key. Requires the X-Auth-Key header to be present. (optional)
/// @param xMessageId This id is used to keep track of the request and its response in the Digital Pay platform. If no value is provided for the request header, Apigee will auto generate an id to use for the request. This header will also be returned in the response and will have the value passed in (or auto generated) from the request. (optional)
/// @param xEverydayPayWallet A flag to indicate if the Everyday Pay wallet should be used when processing the API request. Set the header value to \&quot;true\&quot; to use the Everyday Pay wallet. Set the header value to \&quot;false\&quot; or exclude the header completely to use the default merchant wallet. (optional)
/// @param publicKey The optional ephemeral public key used to encrypt sensitive instrument data and include (&#39;cipherText&#39; in the &#39;meta&#39; object) that encrypted data in the response sent back to the consumer. If this parameter is omitted the sensitive data is NOT returned in the response to the consumer. (optional)
/// 
///  code:200 message:"Successful response"
///
/// @return OAIGetCustomerPaymentInstrumentResult*
-(NSURLSessionTask*) getCustomerPaymentInstrumentWithPaymentInstrumentId: (NSString*) paymentInstrumentId
    xApiKey: (NSString*) xApiKey
    authorization: (NSString*) authorization
    xJWSSignature: (NSString*) xJWSSignature
    xAuthKey: (NSString*) xAuthKey
    xAuthDigest: (NSString*) xAuthDigest
    xMessageId: (NSString*) xMessageId
    xEverydayPayWallet: (NSString*) xEverydayPayWallet
    publicKey: (NSString*) publicKey
    completionHandler: (void (^)(OAIGetCustomerPaymentInstrumentResult* output, NSError* error)) handler;


/// Get Payment Instruments
/// Get the list of payment instruments currently configured for the customer.  Returns an array of instrument records that can be used to execute payments
///
/// @param xApiKey The API key for the request. The API keys (non-prod/prod) will be supplied by the Digital Pay team.
/// @param authorization The Bearer token for the request. The Bearer token authentication approach can be used by API consumers that implement a client-to-server architecture (mobile app, browser site/page) or server-to-server architecture (BFF, microservice, web server, etc.) for calling Digital Pay APIs. However the Bearer token for a shopper/customer must be obtained from the IDM Server Token API which can only be accessed from a server-to-server architecture (BFF, microservice, web server, etc.). The Authorization header is only required if the X-JWS-Signature header is not present.
/// @param xJWSSignature The JWS signature used to sign the request. The JWS signature authentication approach can only be used by API consumers that implement a server-to-server architecture (BFF, microservice, web server, etc.) for calling the Digital Pay APIs. The RSA private key, required to generate the signiture, has to be stored securely and should not be publicly accessible. The X-JWS-Signature header is only required if the Authorization header is not present.
/// @param xAuthKey (Deprecated) You are required to use this header to provide the base64 encoded API key. Requires the X-Auth-Digest header to be present. (optional)
/// @param xAuthDigest (Deprecated) You are required to use this header to provide the encrypted API key. The value is the API key encrypted with the client secret key. Requires the X-Auth-Key header to be present. (optional)
/// @param xMessageId This id is used to keep track of the request and its response in the Digital Pay platform. If no value is provided for the request header, Apigee will auto generate an id to use for the request. This header will also be returned in the response and will have the value passed in (or auto generated) from the request. (optional)
/// 
///  code:200 message:"Successful response"
///
/// @return OAIGetCustomerPaymentInstrumentsResults*
-(NSURLSessionTask*) getCustomerPaymentInstrumentsWithXApiKey: (NSString*) xApiKey
    authorization: (NSString*) authorization
    xJWSSignature: (NSString*) xJWSSignature
    xAuthKey: (NSString*) xAuthKey
    xAuthDigest: (NSString*) xAuthDigest
    xMessageId: (NSString*) xMessageId
    completionHandler: (void (^)(OAIGetCustomerPaymentInstrumentsResults* output, NSError* error)) handler;


/// Get Payment Request details
/// Get the details for a specific payment request so that the customer can pay using it
///
/// @param xApiKey The API key for the request. The API keys (non-prod/prod) will be supplied by the Digital Pay team.
/// @param authorization The Bearer token for the request. The Bearer token authentication approach can be used by API consumers that implement a client-to-server architecture (mobile app, browser site/page) or server-to-server architecture (BFF, microservice, web server, etc.) for calling Digital Pay APIs. However the Bearer token for a shopper/customer must be obtained from the IDM Server Token API which can only be accessed from a server-to-server architecture (BFF, microservice, web server, etc.). The Authorization header is only required if the X-JWS-Signature header is not present.
/// @param xJWSSignature The JWS signature used to sign the request. The JWS signature authentication approach can only be used by API consumers that implement a server-to-server architecture (BFF, microservice, web server, etc.) for calling the Digital Pay APIs. The RSA private key, required to generate the signiture, has to be stored securely and should not be publicly accessible. The X-JWS-Signature header is only required if the Authorization header is not present.
/// @param paymentRequestId The ID of the specific payment request
/// @param xAuthKey (Deprecated) You are required to use this header to provide the base64 encoded API key. Requires the X-Auth-Digest header to be present. (optional)
/// @param xAuthDigest (Deprecated) You are required to use this header to provide the encrypted API key. The value is the API key encrypted with the client secret key. Requires the X-Auth-Key header to be present. (optional)
/// @param xMessageId This id is used to keep track of the request and its response in the Digital Pay platform. If no value is provided for the request header, Apigee will auto generate an id to use for the request. This header will also be returned in the response and will have the value passed in (or auto generated) from the request. (optional)
/// 
///  code:200 message:"Successful response.",
///  code:422 message:"The specified Payment Request ID doesn't exist, has been used or is expired"
///
/// @return OAIGetCustomerPaymentRequestResult*
-(NSURLSessionTask*) getCustomerPaymentRequestDetailsByPaymentIdWithXApiKey: (NSString*) xApiKey
    authorization: (NSString*) authorization
    xJWSSignature: (NSString*) xJWSSignature
    paymentRequestId: (NSString*) paymentRequestId
    xAuthKey: (NSString*) xAuthKey
    xAuthDigest: (NSString*) xAuthDigest
    xMessageId: (NSString*) xMessageId
    completionHandler: (void (^)(OAIGetCustomerPaymentRequestResult* output, NSError* error)) handler;


/// Get Payment Request details from a QR code
/// Get the details for a specific payment from a QR Code ID so that the customer can pay using it
///
/// @param xApiKey The API key for the request. The API keys (non-prod/prod) will be supplied by the Digital Pay team.
/// @param authorization The Bearer token for the request. The Bearer token authentication approach can be used by API consumers that implement a client-to-server architecture (mobile app, browser site/page) or server-to-server architecture (BFF, microservice, web server, etc.) for calling Digital Pay APIs. However the Bearer token for a shopper/customer must be obtained from the IDM Server Token API which can only be accessed from a server-to-server architecture (BFF, microservice, web server, etc.). The Authorization header is only required if the X-JWS-Signature header is not present.
/// @param xJWSSignature The JWS signature used to sign the request. The JWS signature authentication approach can only be used by API consumers that implement a server-to-server architecture (BFF, microservice, web server, etc.) for calling the Digital Pay APIs. The RSA private key, required to generate the signiture, has to be stored securely and should not be publicly accessible. The X-JWS-Signature header is only required if the Authorization header is not present.
/// @param qrId The ID of the specific QR Code
/// @param xAuthKey (Deprecated) You are required to use this header to provide the base64 encoded API key. Requires the X-Auth-Digest header to be present. (optional)
/// @param xAuthDigest (Deprecated) You are required to use this header to provide the encrypted API key. The value is the API key encrypted with the client secret key. Requires the X-Auth-Key header to be present. (optional)
/// @param xMessageId This id is used to keep track of the request and its response in the Digital Pay platform. If no value is provided for the request header, Apigee will auto generate an id to use for the request. This header will also be returned in the response and will have the value passed in (or auto generated) from the request. (optional)
/// 
///  code:200 message:"Successful response.",
///  code:422 message:"The specified QR Code ID doesn't exist or has been expired or the underlying payment request is no longer usable"
///
/// @return OAIGetCustomerPaymentRequestResult*
-(NSURLSessionTask*) getCustomerPaymentRequestDetailsByQRCodeIdWithXApiKey: (NSString*) xApiKey
    authorization: (NSString*) authorization
    xJWSSignature: (NSString*) xJWSSignature
    qrId: (NSString*) qrId
    xAuthKey: (NSString*) xAuthKey
    xAuthDigest: (NSString*) xAuthDigest
    xMessageId: (NSString*) xMessageId
    completionHandler: (void (^)(OAIGetCustomerPaymentRequestResult* output, NSError* error)) handler;


/// Get Payment Session
/// Get the details of a payment session
///
/// @param xApiKey The API key for the request. The API keys (non-prod/prod) will be supplied by the Digital Pay team.
/// @param authorization The Bearer token for the request. The Bearer token authentication approach can be used by API consumers that implement a client-to-server architecture (mobile app, browser site/page) or server-to-server architecture (BFF, microservice, web server, etc.) for calling Digital Pay APIs. However the Bearer token for a shopper/customer must be obtained from the IDM Server Token API which can only be accessed from a server-to-server architecture (BFF, microservice, web server, etc.). The Authorization header is only required if the X-JWS-Signature header is not present.
/// @param xJWSSignature The JWS signature used to sign the request. The JWS signature authentication approach can only be used by API consumers that implement a server-to-server architecture (BFF, microservice, web server, etc.) for calling the Digital Pay APIs. The RSA private key, required to generate the signiture, has to be stored securely and should not be publicly accessible. The X-JWS-Signature header is only required if the Authorization header is not present.
/// @param paymentSessionId The ID of the specific payment session to retrieve
/// @param xAuthKey (Deprecated) You are required to use this header to provide the base64 encoded API key. Requires the X-Auth-Digest header to be present. (optional)
/// @param xAuthDigest (Deprecated) You are required to use this header to provide the encrypted API key. The value is the API key encrypted with the client secret key. Requires the X-Auth-Key header to be present. (optional)
/// @param xMessageId This id is used to keep track of the request and its response in the Digital Pay platform. If no value is provided for the request header, Apigee will auto generate an id to use for the request. This header will also be returned in the response and will have the value passed in (or auto generated) from the request. (optional)
/// 
///  code:200 message:"Successful response",
///  code:422 message:"The specified Payment Session ID doesn't exist or has expired"
///
/// @return OAICustomerPaymentSessionResult*
-(NSURLSessionTask*) getCustomerPaymentSessionWithXApiKey: (NSString*) xApiKey
    authorization: (NSString*) authorization
    xJWSSignature: (NSString*) xJWSSignature
    paymentSessionId: (NSString*) paymentSessionId
    xAuthKey: (NSString*) xAuthKey
    xAuthDigest: (NSString*) xAuthDigest
    xMessageId: (NSString*) xMessageId
    completionHandler: (void (^)(OAICustomerPaymentSessionResult* output, NSError* error)) handler;


/// Get Payment Session
/// Get the payment session associated with the qrId
///
/// @param xApiKey The API key for the request. The API keys (non-prod/prod) will be supplied by the Digital Pay team.
/// @param authorization The Bearer token for the request. The Bearer token authentication approach can be used by API consumers that implement a client-to-server architecture (mobile app, browser site/page) or server-to-server architecture (BFF, microservice, web server, etc.) for calling Digital Pay APIs. However the Bearer token for a shopper/customer must be obtained from the IDM Server Token API which can only be accessed from a server-to-server architecture (BFF, microservice, web server, etc.). The Authorization header is only required if the X-JWS-Signature header is not present.
/// @param xJWSSignature The JWS signature used to sign the request. The JWS signature authentication approach can only be used by API consumers that implement a server-to-server architecture (BFF, microservice, web server, etc.) for calling the Digital Pay APIs. The RSA private key, required to generate the signiture, has to be stored securely and should not be publicly accessible. The X-JWS-Signature header is only required if the Authorization header is not present.
/// @param qrId The ID of the qr relating to the payment session
/// @param xAuthKey (Deprecated) You are required to use this header to provide the base64 encoded API key. Requires the X-Auth-Digest header to be present. (optional)
/// @param xAuthDigest (Deprecated) You are required to use this header to provide the encrypted API key. The value is the API key encrypted with the client secret key. Requires the X-Auth-Key header to be present. (optional)
/// @param xMessageId This id is used to keep track of the request and its response in the Digital Pay platform. If no value is provided for the request header, Apigee will auto generate an id to use for the request. This header will also be returned in the response and will have the value passed in (or auto generated) from the request. (optional)
/// 
///  code:200 message:"Successful response",
///  code:422 message:"The specified Payment Session ID doesn't exist, has been used or is expired"
///
/// @return OAICustomerPaymentSessionResult*
-(NSURLSessionTask*) getCustomerPaymentSessionByQRCodeIdWithXApiKey: (NSString*) xApiKey
    authorization: (NSString*) authorization
    xJWSSignature: (NSString*) xJWSSignature
    qrId: (NSString*) qrId
    xAuthKey: (NSString*) xAuthKey
    xAuthDigest: (NSString*) xAuthDigest
    xMessageId: (NSString*) xMessageId
    completionHandler: (void (^)(OAICustomerPaymentSessionResult* output, NSError* error)) handler;


/// Get Preferences
/// Get the preferences previously set by the customer or merchant (depending on calling identity)
///
/// @param xApiKey The API key for the request. The API keys (non-prod/prod) will be supplied by the Digital Pay team.
/// @param authorization The Bearer token for the request. The Bearer token authentication approach can be used by API consumers that implement a client-to-server architecture (mobile app, browser site/page) or server-to-server architecture (BFF, microservice, web server, etc.) for calling Digital Pay APIs. However the Bearer token for a shopper/customer must be obtained from the IDM Server Token API which can only be accessed from a server-to-server architecture (BFF, microservice, web server, etc.). The Authorization header is only required if the X-JWS-Signature header is not present.
/// @param xJWSSignature The JWS signature used to sign the request. The JWS signature authentication approach can only be used by API consumers that implement a server-to-server architecture (BFF, microservice, web server, etc.) for calling the Digital Pay APIs. The RSA private key, required to generate the signiture, has to be stored securely and should not be publicly accessible. The X-JWS-Signature header is only required if the Authorization header is not present.
/// @param xAuthKey (Deprecated) You are required to use this header to provide the base64 encoded API key. Requires the X-Auth-Digest header to be present. (optional)
/// @param xAuthDigest (Deprecated) You are required to use this header to provide the encrypted API key. The value is the API key encrypted with the client secret key. Requires the X-Auth-Key header to be present. (optional)
/// @param xMessageId This id is used to keep track of the request and its response in the Digital Pay platform. If no value is provided for the request header, Apigee will auto generate an id to use for the request. This header will also be returned in the response and will have the value passed in (or auto generated) from the request. (optional)
/// 
///  code:200 message:"Successful response"
///
/// @return OAICustomerPreferencesResult*
-(NSURLSessionTask*) getCustomerPreferencesWithXApiKey: (NSString*) xApiKey
    authorization: (NSString*) authorization
    xJWSSignature: (NSString*) xJWSSignature
    xAuthKey: (NSString*) xAuthKey
    xAuthDigest: (NSString*) xAuthDigest
    xMessageId: (NSString*) xMessageId
    completionHandler: (void (^)(OAICustomerPreferencesResult* output, NSError* error)) handler;


/// Get Customer Terms and Conditions acceptance
/// Get the terms and conditions agreed to by the customer
///
/// @param xWalletID 
/// @param type The type of Ts and Cs that the shopper/customer has agreed to.  Defaults to all if absent (optional)
/// @param version The version of Ts and Cs that the shopper/customer has agreed to.  Defaults to all if absent (optional)
/// 
///  code:200 message:"Successful Ts and Cs response"
///
/// @return OAICustomerTermsAndConditionsResult*
-(NSURLSessionTask*) getCustomerTermsAndConditionsAcceptanceWithXWalletID: (NSString*) xWalletID
    type: (NSString*) type
    version: (NSString*) version
    completionHandler: (void (^)(OAICustomerTermsAndConditionsResult* output, NSError* error)) handler;


/// Get Transaction Details
/// Get the details for a specific transaction previously executed by the customer.  Note that amounts are relative to the merchant.  A positive amount is a positive amount transferred to a merchant
///
/// @param xApiKey The API key for the request. The API keys (non-prod/prod) will be supplied by the Digital Pay team.
/// @param authorization The Bearer token for the request. The Bearer token authentication approach can be used by API consumers that implement a client-to-server architecture (mobile app, browser site/page) or server-to-server architecture (BFF, microservice, web server, etc.) for calling Digital Pay APIs. However the Bearer token for a shopper/customer must be obtained from the IDM Server Token API which can only be accessed from a server-to-server architecture (BFF, microservice, web server, etc.). The Authorization header is only required if the X-JWS-Signature header is not present.
/// @param xJWSSignature The JWS signature used to sign the request. The JWS signature authentication approach can only be used by API consumers that implement a server-to-server architecture (BFF, microservice, web server, etc.) for calling the Digital Pay APIs. The RSA private key, required to generate the signiture, has to be stored securely and should not be publicly accessible. The X-JWS-Signature header is only required if the Authorization header is not present.
/// @param transactionId The ID of the specific transaction
/// @param xAuthKey (Deprecated) You are required to use this header to provide the base64 encoded API key. Requires the X-Auth-Digest header to be present. (optional)
/// @param xAuthDigest (Deprecated) You are required to use this header to provide the encrypted API key. The value is the API key encrypted with the client secret key. Requires the X-Auth-Key header to be present. (optional)
/// @param xMessageId This id is used to keep track of the request and its response in the Digital Pay platform. If no value is provided for the request header, Apigee will auto generate an id to use for the request. This header will also be returned in the response and will have the value passed in (or auto generated) from the request. (optional)
/// 
///  code:200 message:"Successful response"
///
/// @return OAIGetCustomerTransactionDetailsResults*
-(NSURLSessionTask*) getCustomerTransactionDetailsWithXApiKey: (NSString*) xApiKey
    authorization: (NSString*) authorization
    xJWSSignature: (NSString*) xJWSSignature
    transactionId: (NSString*) transactionId
    xAuthKey: (NSString*) xAuthKey
    xAuthDigest: (NSString*) xAuthDigest
    xMessageId: (NSString*) xMessageId
    completionHandler: (void (^)(OAIGetCustomerTransactionDetailsResults* output, NSError* error)) handler;


/// Get Transaction List
/// Get a list of the previously executed transactions for the customer.  Note that amounts are relative to the merchant.  A positive amount is a positive amount transferred to a merchant
///
/// @param xApiKey The API key for the request. The API keys (non-prod/prod) will be supplied by the Digital Pay team.
/// @param authorization The Bearer token for the request. The Bearer token authentication approach can be used by API consumers that implement a client-to-server architecture (mobile app, browser site/page) or server-to-server architecture (BFF, microservice, web server, etc.) for calling Digital Pay APIs. However the Bearer token for a shopper/customer must be obtained from the IDM Server Token API which can only be accessed from a server-to-server architecture (BFF, microservice, web server, etc.). The Authorization header is only required if the X-JWS-Signature header is not present.
/// @param xJWSSignature The JWS signature used to sign the request. The JWS signature authentication approach can only be used by API consumers that implement a server-to-server architecture (BFF, microservice, web server, etc.) for calling the Digital Pay APIs. The RSA private key, required to generate the signiture, has to be stored securely and should not be publicly accessible. The X-JWS-Signature header is only required if the Authorization header is not present.
/// @param xAuthKey (Deprecated) You are required to use this header to provide the base64 encoded API key. Requires the X-Auth-Digest header to be present. (optional)
/// @param xAuthDigest (Deprecated) You are required to use this header to provide the encrypted API key. The value is the API key encrypted with the client secret key. Requires the X-Auth-Key header to be present. (optional)
/// @param xMessageId This id is used to keep track of the request and its response in the Digital Pay platform. If no value is provided for the request header, Apigee will auto generate an id to use for the request. This header will also be returned in the response and will have the value passed in (or auto generated) from the request. (optional)
/// @param paymentRequestId If present, limits the list of transactions to those that relate to the payment request (optional)
/// @param startTime If present, the date/time to limit transactions returned.  Transactions older than this time will not be returned (optional)
/// @param endTime If present, the date/time to limit transactions returned.  Transactions newer than this time will not be returned (optional)
/// @param pageSize The number of records to return for this page.  Defaults to 25 if absent (optional) (default to @25)
/// @param page The page of results to return with 1 indicating the first page.  Defaults to 1 if absent (optional) (default to @1)
/// 
///  code:200 message:"Successful response"
///
/// @return OAIGetCustomerTransactionsResult*
-(NSURLSessionTask*) getCustomerTransactionsWithXApiKey: (NSString*) xApiKey
    authorization: (NSString*) authorization
    xJWSSignature: (NSString*) xJWSSignature
    xAuthKey: (NSString*) xAuthKey
    xAuthDigest: (NSString*) xAuthDigest
    xMessageId: (NSString*) xMessageId
    paymentRequestId: (NSString*) paymentRequestId
    startTime: (NSDate*) startTime
    endTime: (NSDate*) endTime
    pageSize: (NSNumber*) pageSize
    page: (NSNumber*) page
    completionHandler: (void (^)(OAIGetCustomerTransactionsResult* output, NSError* error)) handler;


/// Get Payment Agreement
/// Get a specific payment agreements
///
/// @param xWalletID 
/// @param paymentToken The ID of the specific payment agreement
/// 
///  code:200 message:"Response for Get, Create and Update Payment Agreements"
///
/// @return OAICustomerPaymentAgreementResponse*
-(NSURLSessionTask*) getPaymentAgreementWithXWalletID: (NSString*) xWalletID
    paymentToken: (NSString*) paymentToken
    completionHandler: (void (^)(OAICustomerPaymentAgreementResponse* output, NSError* error)) handler;


/// Get Payment Agreements
/// Get a list of payment agreements
///
/// @param xWalletID 
/// 
///  code:200 message:"Response for get Payment Agreements list"
///
/// @return OAIPaymentAgreementListResponse*
-(NSURLSessionTask*) getPaymentAgreementListWithXWalletID: (NSString*) xWalletID
    completionHandler: (void (^)(OAIPaymentAgreementListResponse* output, NSError* error)) handler;


/// Initiate Instrument Addition
/// Initiate the addition of a new payment instrument for this customer.  This API returns a URL to be used to access the DigiPay IFrame based interface to request the customer to enter a payment instrument details.
///
/// @param xApiKey The API key for the request. The API keys (non-prod/prod) will be supplied by the Digital Pay team.
/// @param authorization The Bearer token for the request. The Bearer token authentication approach can be used by API consumers that implement a client-to-server architecture (mobile app, browser site/page) or server-to-server architecture (BFF, microservice, web server, etc.) for calling Digital Pay APIs. However the Bearer token for a shopper/customer must be obtained from the IDM Server Token API which can only be accessed from a server-to-server architecture (BFF, microservice, web server, etc.). The Authorization header is only required if the X-JWS-Signature header is not present.
/// @param xJWSSignature The JWS signature used to sign the request. The JWS signature authentication approach can only be used by API consumers that implement a server-to-server architecture (BFF, microservice, web server, etc.) for calling the Digital Pay APIs. The RSA private key, required to generate the signiture, has to be stored securely and should not be publicly accessible. The X-JWS-Signature header is only required if the Authorization header is not present.
/// @param instrumentAdditionDetails 
/// @param xAuthKey (Deprecated) You are required to use this header to provide the base64 encoded API key. Requires the X-Auth-Digest header to be present. (optional)
/// @param xAuthDigest (Deprecated) You are required to use this header to provide the encrypted API key. The value is the API key encrypted with the client secret key. Requires the X-Auth-Key header to be present. (optional)
/// @param xMessageId This id is used to keep track of the request and its response in the Digital Pay platform. If no value is provided for the request header, Apigee will auto generate an id to use for the request. This header will also be returned in the response and will have the value passed in (or auto generated) from the request. (optional)
/// 
///  code:200 message:"Successful response"
///
/// @return OAIInitiatePaymentInstrumentAdditionResults*
-(NSURLSessionTask*) initiatePaymentInstrumentAdditionWithXApiKey: (NSString*) xApiKey
    authorization: (NSString*) authorization
    xJWSSignature: (NSString*) xJWSSignature
    instrumentAdditionDetails: (OAIInstrumentAdditionDetails*) instrumentAdditionDetails
    xAuthKey: (NSString*) xAuthKey
    xAuthDigest: (NSString*) xAuthDigest
    xMessageId: (NSString*) xMessageId
    completionHandler: (void (^)(OAIInitiatePaymentInstrumentAdditionResults* output, NSError* error)) handler;


/// Pay Payment
/// Pay a specific payment using the instrument details provided
///
/// @param xApiKey The API key for the request. The API keys (non-prod/prod) will be supplied by the Digital Pay team.
/// @param authorization The Bearer token for the request. The Bearer token authentication approach can be used by API consumers that implement a client-to-server architecture (mobile app, browser site/page) or server-to-server architecture (BFF, microservice, web server, etc.) for calling Digital Pay APIs. However the Bearer token for a shopper/customer must be obtained from the IDM Server Token API which can only be accessed from a server-to-server architecture (BFF, microservice, web server, etc.). The Authorization header is only required if the X-JWS-Signature header is not present.
/// @param xJWSSignature The JWS signature used to sign the request. The JWS signature authentication approach can only be used by API consumers that implement a server-to-server architecture (BFF, microservice, web server, etc.) for calling the Digital Pay APIs. The RSA private key, required to generate the signiture, has to be stored securely and should not be publicly accessible. The X-JWS-Signature header is only required if the Authorization header is not present.
/// @param paymentRequestId The ID of the specific payment request
/// @param customerPaymentDetails Request payload containing instruments to use for the payment
/// @param xAuthKey (Deprecated) You are required to use this header to provide the base64 encoded API key. Requires the X-Auth-Digest header to be present. (optional)
/// @param xAuthDigest (Deprecated) You are required to use this header to provide the encrypted API key. The value is the API key encrypted with the client secret key. Requires the X-Auth-Key header to be present. (optional)
/// @param xMessageId This id is used to keep track of the request and its response in the Digital Pay platform. If no value is provided for the request header, Apigee will auto generate an id to use for the request. This header will also be returned in the response and will have the value passed in (or auto generated) from the request. (optional)
/// @param xEverydayPayWallet The makes instruments available in the everyday pay wallet available for payments (optional) (default to @(NO))
/// 
///  code:200 message:"Successful response",
///  code:422 message:"The specified Payment Request ID doesn't exist, has been used or is expired"
///
/// @return OAIMakeCustomerPaymentResults*
-(NSURLSessionTask*) makeCustomerPaymentWithXApiKey: (NSString*) xApiKey
    authorization: (NSString*) authorization
    xJWSSignature: (NSString*) xJWSSignature
    paymentRequestId: (NSString*) paymentRequestId
    customerPaymentDetails: (OAICustomerPaymentDetails*) customerPaymentDetails
    xAuthKey: (NSString*) xAuthKey
    xAuthDigest: (NSString*) xAuthDigest
    xMessageId: (NSString*) xMessageId
    xEverydayPayWallet: (NSNumber*) xEverydayPayWallet
    completionHandler: (void (^)(OAIMakeCustomerPaymentResults* output, NSError* error)) handler;


/// Pre-Approve payment
/// Pre-Approve a payment session to make a payment using the instrument details provided
///
/// @param xApiKey The API key for the request. The API keys (non-prod/prod) will be supplied by the Digital Pay team.
/// @param authorization The Bearer token for the request. The Bearer token authentication approach can be used by API consumers that implement a client-to-server architecture (mobile app, browser site/page) or server-to-server architecture (BFF, microservice, web server, etc.) for calling Digital Pay APIs. However the Bearer token for a shopper/customer must be obtained from the IDM Server Token API which can only be accessed from a server-to-server architecture (BFF, microservice, web server, etc.). The Authorization header is only required if the X-JWS-Signature header is not present.
/// @param xJWSSignature The JWS signature used to sign the request. The JWS signature authentication approach can only be used by API consumers that implement a server-to-server architecture (BFF, microservice, web server, etc.) for calling the Digital Pay APIs. The RSA private key, required to generate the signiture, has to be stored securely and should not be publicly accessible. The X-JWS-Signature header is only required if the Authorization header is not present.
/// @param paymentSessionId The ID of the specific payment session
/// @param customerPaymentDetails Request payload containing instruments to use for the payment
/// @param xAuthKey (Deprecated) You are required to use this header to provide the base64 encoded API key. Requires the X-Auth-Digest header to be present. (optional)
/// @param xAuthDigest (Deprecated) You are required to use this header to provide the encrypted API key. The value is the API key encrypted with the client secret key. Requires the X-Auth-Key header to be present. (optional)
/// @param xMessageId This id is used to keep track of the request and its response in the Digital Pay platform. If no value is provided for the request header, Apigee will auto generate an id to use for the request. This header will also be returned in the response and will have the value passed in (or auto generated) from the request. (optional)
/// 
///  code:204 message:"The pre approval has been successfully added to the payment session. No content returned."
///
/// @return void
-(NSURLSessionTask*) preApprovePaymentSessionWithXApiKey: (NSString*) xApiKey
    authorization: (NSString*) authorization
    xJWSSignature: (NSString*) xJWSSignature
    paymentSessionId: (NSString*) paymentSessionId
    customerPaymentDetails: (OAICustomerPaymentDetails*) customerPaymentDetails
    xAuthKey: (NSString*) xAuthKey
    xAuthDigest: (NSString*) xAuthDigest
    xMessageId: (NSString*) xMessageId
    completionHandler: (void (^)(NSError* error)) handler;


/// Set Preferences
/// Change the preferences for the customer or merchant (depending on calling identity)
///
/// @param xApiKey The API key for the request. The API keys (non-prod/prod) will be supplied by the Digital Pay team.
/// @param authorization The Bearer token for the request. The Bearer token authentication approach can be used by API consumers that implement a client-to-server architecture (mobile app, browser site/page) or server-to-server architecture (BFF, microservice, web server, etc.) for calling Digital Pay APIs. However the Bearer token for a shopper/customer must be obtained from the IDM Server Token API which can only be accessed from a server-to-server architecture (BFF, microservice, web server, etc.). The Authorization header is only required if the X-JWS-Signature header is not present.
/// @param xJWSSignature The JWS signature used to sign the request. The JWS signature authentication approach can only be used by API consumers that implement a server-to-server architecture (BFF, microservice, web server, etc.) for calling the Digital Pay APIs. The RSA private key, required to generate the signiture, has to be stored securely and should not be publicly accessible. The X-JWS-Signature header is only required if the Authorization header is not present.
/// @param customerPreferences 
/// @param xAuthKey (Deprecated) You are required to use this header to provide the base64 encoded API key. Requires the X-Auth-Digest header to be present. (optional)
/// @param xAuthDigest (Deprecated) You are required to use this header to provide the encrypted API key. The value is the API key encrypted with the client secret key. Requires the X-Auth-Key header to be present. (optional)
/// @param xMessageId This id is used to keep track of the request and its response in the Digital Pay platform. If no value is provided for the request header, Apigee will auto generate an id to use for the request. This header will also be returned in the response and will have the value passed in (or auto generated) from the request. (optional)
/// 
///  code:204 message:"Preferences successfully updated.  No content returned"
///
/// @return void
-(NSURLSessionTask*) setCustomerPreferencesWithXApiKey: (NSString*) xApiKey
    authorization: (NSString*) authorization
    xJWSSignature: (NSString*) xJWSSignature
    customerPreferences: (OAICustomerPreferences*) customerPreferences
    xAuthKey: (NSString*) xAuthKey
    xAuthDigest: (NSString*) xAuthDigest
    xMessageId: (NSString*) xMessageId
    completionHandler: (void (^)(NSError* error)) handler;


/// Update Payment Agreement
/// Update an existing payment agreement
///
/// @param xWalletID 
/// @param paymentToken The ID of the specific payment agreement
/// @param customerUpdatePaymentAgreementRequest 
/// 
///  code:200 message:"Response for Get, Create and Update Payment Agreements"
///
/// @return OAICustomerPaymentAgreementResponse*
-(NSURLSessionTask*) updateCustomerPaymentAgreementWithXWalletID: (NSString*) xWalletID
    paymentToken: (NSString*) paymentToken
    customerUpdatePaymentAgreementRequest: (OAICustomerUpdatePaymentAgreementRequest*) customerUpdatePaymentAgreementRequest
    completionHandler: (void (^)(OAICustomerPaymentAgreementResponse* output, NSError* error)) handler;



@end
