use_frameworks!

target "VillageWalletSDKOAIClient_Tests" do
  platform :ios, "11.0"

  pod "VillageWalletSDKOAIClient", :path => "../"

  ## FIXME: Use Git for checkout
  pod "VillageWalletSDK", :path => "../../../../ios/sdk/VillageWalletSDK/"

  pod "SwiftHamcrest", "~> 2.2.1"
end
