use_frameworks!

target "VillageWalletSDKOAIClient_Tests" do
  platform :ios, "11.0"

  pod "VillageWalletSDKOAIClient", :path => "../"

  pod "VillageWalletSDK", :git => "git@github.com:w-pay/sdk-wpay-ios.git", :branch => "master"

  pod "SwiftHamcrest", "~> 2.2.1"
end
