use_frameworks!
target "VillageWalletSDKOAIClient_Tests" do
  pod "VillageWalletSDKOAIClient", :path => "../"

  ## FIXME: Use Git for checkout
  pod "VillageWalletSDK", :path => "../../../../ios/sdk/VillageWalletSDK/"
end
